### ISSUE TITLE
Alternate links doesn't work for me

### ISSUE THREAD

**Issue by Daniel-Romero** [kjvarga/sitemap_generator#170]
https://github.com/kjvarga/sitemap_generator#alternate-links
- I have this config file on <code> /config/sitemap/foo.rb</code>

<code>SitemapGenerator::Sitemap.default_host = "http://www.example.com"
SitemapGenerator::Sitemap.create do  add('/index.html', :alternate => {    :href => 'http://www.example.de/index.html',    :lang => 'de',    :nofollow => true  })end</code>
- Then I run this command to refresh my sitemap
  <code>rake sitemap:refresh:no_ping CONFIG_FILE="config/sitemap/foo.rb" </code>
- with this result:

<code>In '/sdasdasda/public/': + sitemap.xml.gz 2 links /  402 Bytes   Sitemap stats: 2 links / 1 sitemaps / 0m00s</code>

If I visit this url I get an xml.gz file with this content
![screen shot 2014-07-16 at 16 35 25](https://cloud.githubusercontent.com/assets/3693265/3600251/87924468-0cf6-11e4-86f4-0723b948f4b7.png)

**Comment by eugenemelnikov** [comment]
Hi, 
Got same thing in all browsers, but only if use alternate links, if without - everything ok. 
Please confirm if its a valid sitemap, or where I can check it.
Thank you.

**Comment by kjvarga** [comment]
Try use a text editor. Browsers cant display xml
in the way you want.

On Tuesday, August 4, 2015, Evgeniy Melnikov <notifications@github.com>
wrote:

> Hi,
> Got same thing in all browsers, but only if use alternate links, if
> without - everything ok.
> Please confirm if its a valid sitemap, or where I can check it.
> Thank you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kjvarga/sitemap_generator/issues/170#issuecomment-127642131>
> .
>


-- 
Karl Varga
e: kjvarga@gmail.com
w: kjvarga.blogspot.com
c: +1.250.884.9895
Skype: kjvarga
