### ISSUE TITLE
Sitemap options with string keys.

### ISSUE THREAD

**Issue by Exoth** [kjvarga/sitemap_generator#176]
It's a little bit annoying that I can't do something like:

    link_set.add('/foo/', 'priority' => 1)

as all the keys in the options hash must be symbols. I keep such options in a yaml configuration file, and I never use symbols in yaml, so in the end I have to do symbolize_keys for the options before sending them to the sitemap_generator.

Can we make it accept options as both symbols and strings?

**Comment by kjvarga** [comment]
Good things are worth waiting for, right?  Maybe this isn't good enough lol.  But this is now supported in 5.2.0
