### ISSUE TITLE
SitemapGenerator::SitemapFullError

### ISSUE THREAD

**Issue by beingmattlevy** [kjvarga/sitemap_generator#184]
I am hitting an issue where I am using groups and somehow hitting the 50K sitemap index issue. 

First the error trace:
The error trace on adding link 50001: 

rake aborted!
SitemapGenerator::SitemapFullError: SitemapGenerator::SitemapFullError
/Users/matt/.rvm/gems/ruby-1.9.3-p429@betterdoctor-web/gems/sitemap_generator-5.0.5/lib/sitemap_generator/builder/sitemap_file.rb:103:in `add'
/Users/matt/.rvm/gems/ruby-1.9.3-p429@betterdoctor-web/gems/sitemap_generator-5.0.5/lib/sitemap_generator/builder/sitemap_index_file.rb:67:in `add'
/Users/matt/.rvm/gems/ruby-1.9.3-p429@betterdoctor-web/gems/sitemap_generator-5.0.5/lib/sitemap_generator/link_set.rb:162:in `add_to_index'
/Users/matt/.rvm/gems/ruby-1.9.3-p429@betterdoctor-web/gems/sitemap_generator-5.0.5/lib/sitemap_generator/link_set.rb:454:in `finalize_sitemap!'
/Users/matt/.rvm/gems/ruby-1.9.3-p429@betterdoctor-web/gems/sitemap_generator-5.0.5/lib/sitemap_generator/link_set.rb:234:in `group'
/Users/matt/.rvm/gems/ruby-1.9.3-p429@betterdoctor-web/gems/sitemap_generator-5.0.5/lib/sitemap_generator/interpreter.rb:43:in `group'
/Users/matt/Sandbox/src.betterdoctor-web/lib/tasks/sitemap.rake:166:in `block (2 levels) in generate_sitemap'
/Users/matt/.rvm/gems/ruby-1.9.3-p429@betterdoctor-web/gems/mongoid-3.1.6/lib/mongoid/contextual/mongo.rb:640:in `yield_document'
/Users/matt/.rvm/gems/ruby-1.9.3-p429@betterdoctor-web/gems/mongoid-3.1.6/lib/mongoid/contextual/mongo.rb:123:in `block (2 levels) in each'
/Users/matt/.rvm/gems/ruby-1.9.3-p429@betterdoctor-web/gems/moped-1.5.2/lib/moped/query.rb:77:in `block in each'
/Users/matt/.rvm/gems/ruby-1.9.3-p429@betterdoctor-web/gems/moped-1.5.2/lib/moped/cursor.rb:30:in `block in each'
/Users/matt/.rvm/gems/ruby-1.9.3-p429@betterdoctor-web/gems/moped-1.5.2/lib/moped/cursor.rb:30:in `each'
/Users/matt/.rvm/gems/ruby-1.9.3-p429@betterdoctor-web/gems/moped-1.5.2/lib/moped/cursor.rb:30:in `each'
/Users/matt/.rvm/gems/ruby-1.9.3-p429@betterdoctor-web/gems/moped-1.5.2/lib/moped/query.rb:76:in `each'
/Users/matt/.rvm/gems/ruby-1.9.3-p429@betterdoctor-web/gems/moped-1.5.2/lib/moped/query.rb:76:in `each'
/Users/matt/.rvm/gems/ruby-1.9.3-p429@betterdoctor-web/gems/mongoid-3.1.6/lib/mongoid/contextual/mongo.rb:122:in `block in each'
/Users/matt/.rvm/gems/ruby-1.9.3-p429@betterdoctor-web/gems/mongoid-3.1.6/lib/mongoid/contextual/mongo.rb:619:in `selecting'
/Users/matt/.rvm/gems/ruby-1.9.3-p429@betterdoctor-web/gems/mongoid-3.1.6/lib/mongoid/contextual/mongo.rb:121:in `each'
/Users/matt/.rvm/gems/ruby-1.9.3-p429@betterdoctor-web/gems/mongoid-3.1.6/lib/mongoid/contextual.rb:19:in `each'
/Users/matt/Sandbox/src.betterdoctor-web/lib/tasks/sitemap.rake:149:in `each_with_index'
/Users/matt/Sandbox/src.betterdoctor-web/lib/tasks/sitemap.rake:149:in `block in generate_sitemap'
/Users/matt/.rvm/gems/ruby-1.9.3-p429@betterdoctor-web/gems/sitemap_generator-5.0.5/lib/sitemap_generator/interpreter.rb:59:in `instance_eval'
/Users/matt/.rvm/gems/ruby-1.9.3-p429@betterdoctor-web/gems/sitemap_generator-5.0.5/lib/sitemap_generator/interpreter.rb:59:in `eval'
/Users/matt/.rvm/gems/ruby-1.9.3-p429@betterdoctor-web/gems/sitemap_generator-5.0.5/lib/sitemap_generator/link_set.rb:40:in `create'
/Users/matt/.rvm/gems/ruby-1.9.3-p429@betterdoctor-web/gems/sitemap_generator-5.0.5/lib/sitemap_generator.rb:42:in `method_missing'
/Users/matt/Sandbox/src.betterdoctor-web/lib/tasks/sitemap.rake:77:in `generate_sitemap'
/Users/matt/Sandbox/src.betterdoctor-web/lib/tasks/sitemap.rake:17:in `block (2 levels) in <top (required)>'
Tasks: TOP => sitemap:generate
(See full trace by running task with --trace)

Here is my code producing the error I keep hitting:
```ruby
SitemapGenerator::Sitemap.default_host = 'https:/betterdoctor.com'
SitemapGenerator::Sitemap.public_path = 'public/utils/'
SitemapGenerator::Sitemap.sitemaps_path = 'sitemaps/'
SitemapGenerator::Sitemap.create_index = true
SitemapGenerator::Sitemap.verbose = true

SitemapGenerator::Sitemap.create do
    static_paths.each do |path|
        add path, :changefreq => change_frequency    
     end
     doctor_links = 0
     Doctor.limit(link_limit).only(:'profile.slugs', :updated_at).each_with_index do |doctor, index|
         doctor_links += 1
         group(:filename => :doctors, :sitemaps_path => "sitemaps/doctors/") do
              add "/#{doctor.slug}", :lastmod => doctor.updated_at
         end
     end
end
```

**Comment by kjvarga** [comment]
Sorry I just saw this now.  Yes you're creating a new file for each doctor (!!) so you're running into the maximum number of files limit.  Moving the group outside the each fixes it because now you're doing it right :)

**Comment by beingmattlevy** [comment]
Thanks for the confirmation I am doing it the right way now. :)
