### ISSUE TITLE
SitemapGenerator::Sitemap.default_host shows a url/uri in the docs.

### ISSUE THREAD

**Issue by dogweather** [kjvarga/sitemap_generator#186]
This setting should either change, i.e. `default_url`, or we should change the docs to show a hostname.

"Every sitemap must set default_host. This is the hostname that is used when building links to add to the sitemap (and all links in a sitemap must belong to the same host)."

**Comment by kjvarga** [comment]
Yeah technically it's a URL because it includes the protocol.  But I don't think it's a big deal.
