### ISSUE TITLE
Dynamic Sitemap

### ISSUE THREAD

**Issue by Hamdan85** [kjvarga/sitemap_generator#190]
Is is possible to make this gem be dynamic? Because if I generated a sitemap on my development environment, it will be wrong right?

**Comment by pavankat** [comment]
I suspect this is the case @Hamdan85. An alternative approach is installing this and generating the file on your server, then downloading it and then putting it in your repository. That sounds like a bitch though.

**Comment by Hamdan85** [comment]
wow.. so this gem is kinda (im sorry, not mean to be disrespectful) useless
since it cannot be dynamic on a framework that is supposed to develop
dynamic applications... lol right?

2015-02-23 19:46 GMT-03:00 Pavan Katepalli <notifications@github.com>:

**Comment by pavankat** [comment]
@Hamdan85 What i'm doing is using https://github.com/kjvarga/sitemap_generator in conjunction with this: http://blog.arkency.com/2014/02/sitemaps-with-a-bit-of-metal/

The alternative easier approach is by doing something like this: https://salayhin.wordpress.com/2013/10/29/create-dynamic-sitemap-on-ruby-on-rails/ 

however it could take some time to load if you have a lot routes. I have 14k urls so I'm going with the first option.

**Comment by Hamdan85** [comment]
i think ill make it by myself in a controller. its easier than this way.

2015-02-24 1:18 GMT-03:00 Pavan Katepalli <notifications@github.com>:

**Comment by PikachuEXE** [comment]
I do a redirect for `/sitemap.xml`, controller code:
```ruby
class SeoController < ApplicationController
  layout false

  # Only do redirects to sitemap index on S3
  def sitemap
    # This is some app specific logic, you can just use `request.host`
    current_domain = Domain.sanitized_directly_accessible_domain(request.host)
    
    # you need to change these lines according to your `sitemap_generator` config
    SitemapGenerator::Sitemap.default_host = "http://#{current_domain}"
    # .sitemaps_host must be set again after setting .default_host
    SitemapGenerator::Sitemap.sitemaps_host = "http://#{Rails.application.secrets.aws_s3_bucket_name}.s3.amazonaws.com/"
    # My app serves multiple TLD, hence this line
    SitemapGenerator::Sitemap.sitemaps_path = "sitemaps/#{current_domain}"

    redirect_to SitemapGenerator::Sitemap.sitemap_index_url
  end
end
```

I also use similar code for my `robots.txt` (generated by [`human_power`](https://github.com/lassebunk/human_power))

**Comment by kjvarga** [comment]
@Hamdan85 "dynamic" sitemaps are generally a bad idea.  It's far safer, simpler and more efficient to pre-generate your sitemaps on a schedule that you set up and have search engines access your sitemaps via static file.  Dynamic sitemaps simply do not work for sites of any decent size.

Thanks for the code @PikachuEXE I'm sure that will be helpful for others.

**Comment by Hamdan85** [comment]
Why it would be a bad idea? Because of attacks?

2015-05-13 16:39 GMT-03:00 Karl Varga <notifications@github.com>:

**Comment by PikachuEXE** [comment]
If "dynamic sitemap" means a sitemap generated on request (either cached afterward or not),
then it will have performance issue for any application with many routes that needs to be included in sitemap.

If "dynamic sitemap" means redirecting to existing sitemap file(s), then it's fine.

I am doing the 2nd one. See my code for redirecting in my comment above.
If you want to know how to generate sitemaps periodically (those pointed by redirection), please ping me here. (It might be long, so I don't want to post unless someone needs it)

**Comment by Hamdan85** [comment]
Actually I do not want to bother with it until it becomes a problem you
know? lol

2015-05-15 2:12 GMT-03:00 PikachuEXE <notifications@github.com>:

**Comment by PikachuEXE** [comment]
Guess this gem is not for you
I used to just generate it myself (or there might be some gems supporting runtime generation)

**Comment by Hamdan85** [comment]
I just created it myself.

2015-05-15 11:40 GMT-03:00 PikachuEXE <notifications@github.com>:
