### ISSUE TITLE
No DOCTYPE Declaration Found!

### ISSUE THREAD

**Issue by IslamAzab** [kjvarga/sitemap_generator#192]
I was trying to validate my sitemaps by w3 validator [link](http://validator.w3.org/check)

> No DOCTYPE found! Checking XML syntax only.
> The DOCTYPE Declaration was not recognized or is missing. This probably means that the Formal Public Identifier contains a spelling error, or that the Declaration is not using correct syntax, or that your XML document is not using a DOCTYPE Declaration.

> Validation of the document has been skipped, and a simple check of the well-formedness of the XML syntax has been performed instead.

> Learn how to add a doctype to your document from our FAQ, or use the validator's option to validate your XML document against a specific Document Type

http://validator.w3.org/docs/help.html#faq-doctype

**Comment by kjvarga** [comment]
The W3C validator validates XHTML not XML.  Hence the warning about DOCTYPE.
