### ISSUE TITLE
rake sitemap:clean does not work when SitemapGenerator::Sitemap.sitemaps_path is set

### ISSUE THREAD

**Issue by drh-stanford** [kjvarga/sitemap_generator#193]
When I set

```
  SitemapGenerator::Sitemap.sitemaps_path = 'sitemaps/'
```

the `rake sitemap:clean` still tries to remove everything from `public/sitemap*.xml.gz`.

See https://github.com/kjvarga/sitemap_generator/blob/master/lib/sitemap_generator/utilities.rb#L25

**Comment by kjvarga** [comment]
That's correct.  There's no way to have this work with custom configurations (without some effort, which I don't think is worth it).  So I may just remove that route.
