### ISSUE TITLE
Issues with AWS and Fog

### ISSUE THREAD

**Issue by taylorscollon** [kjvarga/sitemap_generator#194]
I had an issue getting this to work with Fog and AWS for sitemaps on Heroku. 

I was getting 400 Bad Request errors whenever I ran rake sitemap:refresh. 

The problem was that your AWS region has to be explicitly set as a environment variable (i.e. FOG_REGION = us-west-2)

This isn't in the docs yet, but might help someone avoid a bit of searching.

**Comment by HansHauge** [comment]
:+1:

**Comment by alpemaca** [comment]
:+1:

**Comment by kjvarga** [comment]
Odd that you had to do that as I thought you didn't have to include it if your region is us-west-2 (the default).  At least that's a comment I had in https://github.com/kjvarga/sitemap_generator/wiki/Generate-Sitemaps-on-read-only-filesystems-like-Heroku

I'll update it.  Thanks
