### ISSUE TITLE
Excluding URLs

### ISSUE THREAD

**Issue by grouptable** [kjvarga/sitemap_generator#195]
We have a certain number of URLs which are html-tagged 'noindex' for search engines. However,sitemap, generated using this this gem, includes such URLs. This is likely to send conflicting signals to search engines. Is there any way to exclude 'noindex URLs' from the sitemap?

**Comment by abrambailey** [comment]
I'm not sure why this issue is closed. Is there a way to exclude links from resourceful route inside of this gem?

**Comment by kjvarga** [comment]
You have to include only the links you want in your sitemap.  Is there a
reason you aren't able to do that?
