### ISSUE TITLE
NoMethodError (To respond to a custom format,

### ISSUE THREAD

**Issue by legolytics** [kjvarga/sitemap_generator#197]
I am getting the following error when downloading the sitemap file.

```NoMethodError (To respond to a custom format, register it as a MIME type first: http://guides.rubyonrails.org/action_controller_overview.html#restful-downloads. If you meant to respond to a variant like :tablet or :phone, not a custom format, be sure to nest your variant response within a format response: format.html { |html| html.tablet { ... } }):```

sitemap generator verson 5.0.5
rails version: 4.2

rake sitemap:create generated all sitemap files correctly. I am using ActiceRecordAdapter for storage.

what am I doing wrong?

**Comment by kjvarga** [comment]
Well it seems you're trying to access the sitemap file through Rails.  Once you've generated your sitemap files into your public/ directory, you should be able to access them outside of rails (the same as your application access its image and javascript resources).  You're either not configuring the 'public' directory as a static file directory correctly in your web server (see your rackup file), or you've put the files in a directory under Rails.
