### ISSUE TITLE
Ping by default, but with custom sitemap_index_url?

### ISSUE THREAD

**Issue by brchristian** [kjvarga/sitemap_generator#199]
I'm curious to know: is it possible to have `sitemap:refresh` ping using a custom `sitemap_index_url`?

From my reading so far, it appears that it's only possible to specify the `sitemap_index_url` if I call the `ping_search_engines` method manually, but that would involve my using two different rake tasks -- one to do `sitemap:refresh:no_ping` and a second to do `ping_search_engines` while passing in a `sitemap_index_url`.  I'm wondering if there's a cleaner way.

Thanks!

**Comment by kjvarga** [comment]
If you use `rake sitemap:refresh` it will ping with the correct sitemap index url, even if you have a custom config.  Does that work for you?

**Comment by kjvarga** [comment]
There are a few different ways to do it manually.  It knows what your sitemaps index url is if you call `SitemapGenerator::Sitemap.ping_search_engines` at the end of your sitemap config.

**Comment by brchristian** [comment]
@kjvarga We set `SitemapGenerator::Sitemap.sitemaps_host` to an Amazon S3 bucket, but I'd like to give the search engines a URL from our own site that's set up to serve that file (rather than giving the search engines the S3 bucket path). What is the best way to do something like that?

**Comment by kjvarga** [comment]
Your sitemaps_host should still be set to the URL of your website,
otherwise the links that are generated in your sitemaps will be invalid
(they'll be pointing to your S3 bucket which doesn't make any sense?).  Can
you paste in your config, I don't understand what you're doing.

On Thu, Jun 11, 2015 at 10:28 AM, brchristian <notifications@github.com>
wrote:

> @kjvarga <https://github.com/kjvarga> We set
> SitemapGenerator::Sitemap.sitemaps_host to an Amazon S3 bucket, but I'd
> like to give the search engines a URL from our own site that's set up to
> serve that file (rather than giving the search engines the S3 bucket path).
> What is the best way to do something like that?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kjvarga/sitemap_generator/issues/199#issuecomment-111213937>
> .
>



-- 
Karl Varga
e: kjvarga@gmail.com
w: kjvarga.blogspot.com
c: +1.250.884.9895
Skype: kjvarga

**Comment by brchristian** [comment]
@kjvarga I appreciate you taking the time to help. Our sitemap links look reasonable, so that part looks okay. Let me show you what the config looks like:

    if Rails.env.production? # Don't upload sitemaps to S3 in development
      SitemapGenerator::Sitemap.adapter = SitemapGenerator::S3Adapter.new(
        fog_provider: 'AWS',
        aws_access_key_id: 'access_key',
        aws_secret_access_key: 'secret_access_key',
        fog_directory: 'fog_directory',
        fog_region: 'fog_region'
      )
    end
                                      
    # Set the host name for URL creation
    SitemapGenerator::Sitemap.default_host = "http://www.myapp.com"
    # pick a place safe to write the files
    SitemapGenerator::Sitemap.public_path = 'tmp/'
    # inform the map cross-linking where to find the other maps
    SitemapGenerator::Sitemap.sitemaps_host = "https://s3bucketname.cloudfront.net/"
    # pick a namespace within your bucket to organize your maps
    SitemapGenerator::Sitemap.sitemaps_path = 'sitemaps/'

We use the `sitemaps/` folder within our S3 bucket, and have a route in `config/routes.rb` that matches `http://www.myapp.com/sitemap.xml.gz` to `https://s3bucketname.cloudfront.net/sitemaps/sitemap.xml.gz`.

At the moment all the links in the sitemap correctly point to addresses at the `http://www.myapp.com` URL, and the file correctly uploads to S3. However it appears that the sitemap URL being given to the search engines is the `cloudfront.net` URL, and I'd love to give `http://www.myapp.com/sitemap.xml.gz` instead.

**Comment by kjvarga** [comment]
Ah.  Sorry I spaced out on sitemaps_host vs default_host.  You're doing it
right.  The url used in the ping will be the one on cloudfront.net because
that is where the sitemap files live.

I assume you are using some method of proxy'ing the S3 files on myapp.com
so that  http://www.myapp.com/sitemap.xml.gz is a valid link.

The easiest way to do what you want is to generate sitemaps with `rake
sitemap:refresh:no_ping` and append this to the end of your sitemap config:

SitemapGenerator::Sitemap.ping_search_engines('
http://www.myapp.com/sitemap.xml.gz')

Does that do what you want?

On Thu, Jun 11, 2015 at 10:42 AM, brchristian <notifications@github.com>
wrote:

> @kjvarga <https://github.com/kjvarga> I appreciate you taking the time to
> help. Our sitemap links look reasonable, so that part looks okay. Let me
> show you what the config looks like:
>
> if Rails.env.production? # Don't upload sitemaps to S3 in development
>   SitemapGenerator::Sitemap.adapter = SitemapGenerator::S3Adapter.new(
>     fog_provider: 'AWS',
>     aws_access_key_id: 'access_key',
>     aws_secret_access_key: 'secret_access_key',
>     fog_directory: 'fog_directory',
>     fog_region: 'fog_region'
>   )
> end
>
> # Set the host name for URL creation
> SitemapGenerator::Sitemap.default_host = "http://www.myapp.com"
> # pick a place safe to write the files
> SitemapGenerator::Sitemap.public_path = 'tmp/'
> # inform the map cross-linking where to find the other maps
> SitemapGenerator::Sitemap.sitemaps_host = "https://s3bucketname.cloudfront.net/"
> # pick a namespace within your bucket to organize your maps
> SitemapGenerator::Sitemap.sitemaps_path = 'sitemaps/'
>
> We use the sitemaps/ folder within our S3 bucket, and have a route in
> config/routes.rb that matches http://www.myapp.com/sitemap.xml.gz to
> https://s3bucketname.cloudfront.net/sitemaps/sitemap.xml.gz.
>
> At the moment all the links in the sitemap correctly point to addresses at
> the http://www.myapp.com URL, and the file correctly uploads to S3.
> However it appears that the sitemap URL being given to the search engines
> is the cloudfront.net URL, and I'd love to give
> http://www.myapp.com/sitemap.xml.gz instead.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kjvarga/sitemap_generator/issues/199#issuecomment-111218663>
> .
>



-- 
Karl Varga
e: kjvarga@gmail.com
w: kjvarga.blogspot.com
c: +1.250.884.9895
Skype: kjvarga

**Comment by brchristian** [comment]
> I assume you are using some method of proxy'ing the S3 files on myapp.com so that  http://www.myapp.com/sitemap.xml.gz is a valid link.

Yep, we just have a line in `config/routes.rb`:

    get '/sitemap.xml.gz', to: redirect('https://s3bucketname.cloudfront.net/sitemaps/sitemap.xml.gz'), as: :sitemap

Okay, so after the `SitemapGenerator::Sitemap.create do` block, I just say

    SitemapGenerator::Sitemap.ping_search_engines(sitemap_url)

And it all works! Thanks so much for your help!
