### ISSUE TITLE
Alternate Links does not works properly

### ISSUE THREAD

**Issue by diegodurante** [kjvarga/sitemap_generator#203]
Hi everybody,
If we try to create links using alternate links feature as reported into official documentation, the xml file generated is broken.

Tryed to create a sitemap.rb with just the code reported into official documentation:
**config/sitemap.rb**

    SitemapGenerator::Sitemap.default_host = "http://www.example.com"
      SitemapGenerator::Sitemap.create do
        add('/index.html', :alternate => {
          :href => 'http://www.example.de/index.html',
          :lang => 'de',
          :nofollow => true
        })
    end

Run the command: **rake sitemap:refresh** and got a sitemap.xml file with this output:

<img width="908" alt="screen shot 2015-07-15 at 15 31 14" src="https://cloud.githubusercontent.com/assets/2998604/8699837/a0ebabda-2b08-11e5-9264-0b36c1ac42aa.png">

**That of course is not an XML format.**

Instead having a simple sitemap.rb file like this:

    SitemapGenerator::Sitemap.default_host = "http://www.example.com"
      SitemapGenerator::Sitemap.create do
        add '/index.html',  priority: 1,   changefreq: 'daily'
    end

Will produce a correct XML file like this:

<img width="1036" alt="screen shot 2015-07-15 at 15 48 30" src="https://cloud.githubusercontent.com/assets/2998604/8699896/047fa926-2b09-11e5-90ea-2d4361fefd5d.png">

Tested with these versions:
- Ruby 2.1.3
- Rails 4.2.3
- sitemap_generator: 5.0.5

What is going on?
Thanks,
Diego.

**Comment by kjvarga** [comment]
I've run the same test with the same versions and it works as it should.

Are you viewing the xml file in a browser?  Only the contents of the XML elements will be shown, and not the element tags themselves.
