### ISSUE TITLE
How can changefreq be modified for root url?

### ISSUE THREAD

**Issue by barcala** [kjvarga/sitemap_generator#205]
Hi all:
I want to modify changefreq property for root url in my sitemap.xml. If I write something like:

```ruby
SitemapGenerator::Sitemap.create do
  add '/', :changefreq => 'monthly'
end
```
or even
```ruby
SitemapGenerator::Sitemap.create do
  add '', :changefreq => 'monthly'
end
```
I get two different entries for the same root url inside sitemap.xml. Is it possible to modify sitemap default parameters for root url?

I'm using sitemap_generator 5.1.0 and ruby 2.1.6.

Thank you,

**Comment by kjvarga** [comment]
Turn off automatic root url inclusion and then you can add it yourself with:

```
SitemapGenerator::Sitemap.include_root = false
SitemapGenerator::Sitemap.create do
  add '/', :changefreq => 'monthly'
end
```
