### ISSUE TITLE
Dynamic configuration of default_host, sitemaps_path, etc.

### ISSUE THREAD

**Issue by lime** [kjvarga/sitemap_generator#207]
In an app that serves multiple domains, I generate sitemaps along these lines:

```ruby
Site.each do |site|
  SitemapGenerator::Sitemap.default_host = site.host
  SitemapGenerator::Sitemap.sitemaps_path = site.locale.to_s
  SitemapGenerator::Sitemap.create do
    ...
  end
end
```
In robots.txt, I'd like to output
```erb
Sitemap: <%= SitemapGenerator::Sitemap.sitemap_index_url %>
```

However, that won't work since `default_host` and `sitemaps_path` are set only during sitemap generation, and I can't set them globally as they differ depending on the current site.

If we were to change the configuration to accept lambdas, I could set `default_host` in an initializer:
```ruby
SitemapGenerator::Sitemap.default_host = -> { Site.current.host }
SitemapGenerator::Sitemap.sitemaps_path = -> { Site.current.locale.to_s }
```

Is that something you would be willing to consider?

**Comment by kjvarga** [comment]
How are you writing out your robots.txt file, or is it served by a Rails controller action?  I assume the latter. The location of the index file never changes, so you could simply do:
```
Sitemap: <%= URI.join(Site.current.host, Site.current.locale.to_s, 'sitemap.xml.gz' %>
```

**Comment by lime** [comment]
Thanks for the reply, @kjvarga. Workarounds for this use case, like the one you mention, definitely exist. For the most part, they require me to repeat the location settings in two separate places.

My setup is now in fact somewhat more complex than in the original post. In production & staging I upload the sitemap to S3, while in development it is served locally.
```ruby
  SitemapGenerator::Sitemap.sitemaps_host = ENV['SITEMAPS_HOST']
  SitemapGenerator::Sitemap.adapter = SitemapGenerator::S3Adapter.new
```

This means that the logic for building the sitemap URL will vary depending on the environment, whether `sitemaps_host`/`default_host` is set, etc. All of this is already provided by `sitemap_index_url` (yay), which uses the global configuration, which in turn is static.

---

I can elaborate on my setup if it helps in establishing potential use cases. I have however monkey-patched my way around the URL generation issue, so we don't necessarily need to focus specifically on that.

I had a look at the `LinkSet` source, and I get the feeling that allowing lambdas in the configuration would clutter things up a bit. If you are open to the idea, maybe a separate `Configuration` module would be a better place for storing those options.

What are your thoughts?

**Comment by kjvarga** [comment]
So you want run-time configuration of your sitemap.  I think a simpler and easier way to do that would be something like:

```
# application.rb
module YourApp
  class Application
    def sitemap(site)
      sitemap = SitemapGenerator::LinkSet.new
      sitemap.default_host = site.host
      sitemap.sitemaps_path = site.locale.to_s
      if Rails.env.to_sym != :development
        sitemap.sitemaps_host = ENV['SITEMAPS_HOST']
        sitemap.adapter = SitemapGenerator::S3Adapter.new
      end
      sitemap
    end
  end
end

# robots.txt
Sitemap: <%= Rails.app.sitemap.sitemap_index_url %>

# config/sitemap.rb
Site.each do |site|
  Rails.app.sitemap(site).create do
    ...
  end
end
```

I considered putting that method on the Site model which is a nice looking option as long as the Rails env is passed as an argument e.g. `Site.current.sitemap(Rails.env.to_sym).sitemap_index_url`

**Comment by lime** [comment]
That looks like quite a pleasant approach. Thank you for the suggestion!

It might very well be that runtime configuration is a specific enough need that it is better solved on a case by case basis. If the need arises for dynamic configuration options, let me know and I'll take a stab at it.

**Comment by kjvarga** [comment]
Thanks for the offer.

**Comment by kjvarga** [comment]
BTW I fixed a mistake in the robots.txt line above...should have passed in Site.current
