### ISSUE TITLE
documetnation about fog-aws gem 

### ISSUE THREAD

**Issue by jjb** [kjvarga/sitemap_generator#210]
Including fog-aws in one's Gemfile is required when persisting to S3, right?

I don't think this is ever explicitely mentioned in the docs, and is sort of incorrectly represented in the error message here: https://github.com/kjvarga/sitemap_generator/commit/943c7a01896f7c55177bb1a251d2dbd3c03ccdf5

I'm happy to submit a PR and update the wiki fixing these things, but just double-checking first.

Thanks!

**Comment by kjvarga** [comment]
The error message was fixed to indicate that only the `fog-aws` gem is required.  https://github.com/kjvarga/sitemap_generator/blob/master/lib/sitemap_generator/adapters/s3_adapter.rb

If you'd like to add a note to the wiki that would be great.

**Comment by jjb** [comment]
done! https://github.com/kjvarga/sitemap_generator/wiki/Generate-Sitemaps-on-read-only-filesystems-like-Heroku/_compare/259aab1dba7424ff063326b6df203101ba7830ea...3541de184a47a0d4de6179bc3334198c81e3d843

not sure if the same change should go here: https://github.com/kjvarga/sitemap_generator/wiki/Uploading-the-sitemap-to-S3-with-paperclip,-aws-s3-and-aws-sdk

**Comment by kjvarga** [comment]
Thanks!

That other wiki entry was created by someone else so no need to change it.
