### ISSUE TITLE
I don't like the .gz extension. Is it possible to disable it?

### ISSUE THREAD

**Issue by thedanotto** [kjvarga/sitemap_generator#213]
Hey,

I'm looking to disable the automatic .gz extension for sitemap_generator. Is that possible? I wasn't able to find anything in the documentation.

I apologize if I've posted this in the wrong area and/or made anyone angry.

Thanks from a nub,
Dan

**Comment by kjvarga** [comment]
You can use the `compress` option.  See https://github.com/kjvarga/sitemap_generator#customizing-your-sitemaps.

E.g. `SitemapGenerator::Sitemap.compress = false`
