### ISSUE TITLE
default_host different for index than non index

### ISSUE THREAD

**Issue by rushingfitness** [kjvarga/sitemap_generator#215]
So I have a custom processor that sets the default_host to `www.example.com`. All of my links are on that site.
However the index xml file needs to point to `cdn.example.com`
Is there a way to differentiate the two urls that I'm not seeing?

Thanks guys!

**Comment by kjvarga** [comment]
You want to use the `sitemaps_host` option.  See https://github.com/kjvarga/sitemap_generator#sitemap-options

E.g. `SitemapGenerator::Sitemap.sitemaps_host = 'http://cdn.example.com'`
