### ISSUE TITLE
`rake sitemap:refresh` fails silently when WaveAdapter is incorrectly configured.

### ISSUE THREAD

**Issue by radavis** [kjvarga/sitemap_generator#216]
`rake sitemap:refresh` is supposed to generate a sitemap, and upload it to a remote server if the WaveAdapter is configured. However, it fails silently if not properly configured. 

```
In '/Users/rd/app-name/tmp/':
+ sitemaps/sitemap.xml.gz                                  8 links /  438 Bytes
Sitemap stats: 8 links / 1 sitemaps / 0m00s

Pinging with URL 'https://s3.amazonaws.com/s3-bucket/sitemaps/sitemap.xml.gz':
  Successful ping of Google
  Successful ping of Bing
```

Upon checking S3, nothing is there. Output from `rake sitemap:refresh` doesn't indicate a problem.

**Comment by kjvarga** [comment]
This appears to be a failing of the WaveAdapter.  I think there must be a way for you to turn on some debugging in the Wave config so you get more output.  But if the Wave adapter doesn't throw an error there's little I can do.
