### ISSUE TITLE
Automatic timestamp generation

### ISSUE THREAD

**Issue by GreyCat** [kjvarga/sitemap_generator#218]
`add` method allows to specify last modification date to be included into sitemap using `:lastmod` key. However, I find this construction *really* awkward:

    Content.find_each do |content|
      add content_path(content), :lastmod => content.updated_at
    end

In most real-life tasks, `content_path` that renders `Content` for end users relies on complex tree of dependent entities. For example, article might include a link to author and a list of comments. When author changes, even if article itself hasn't changed, we still need to update timestamp — it's done both for caching / ETag purposes and it's the very same timestamp that should be used in sitemap.

My point is that controller already performs this logic: it performs multiple complex queries to derive timestamp and I don't want to duplicate this logic in sitemap generation code. It's fairly trivial to call controller method referenced by `content_path` and get `:lastmod` date from it. Therefore, I propose to add some magic value, like `:lastmod => :auto` or `:lastmod => :controller` that will do so.

The only downside I see is that it will obviously dramatically slow down sitemap generation due to controller calling + SQL querying one-by-one overhead.

**Comment by kjvarga** [comment]
If you have written it why not call it with your record and get the timestamp you desire and pass this in the call to `add`?  It sounds like this should be a method on your model rather than in a controller.  But as long as you make the method callable, you can do something like:

E.g. `add content_path(content), lastmod: content.get_complex_last_modified_timestamp`

**Comment by GreyCat** [comment]
Unfortunately, it's not just a method of a model: in reality, querying most controllers return a complex structure of several model objects for rendering purposes.

For example, if we consider your average ecommerce product page, besides information on product itself, it usually pulls up some vendor data, some cross-sales data, some reviews, etc. Vendor might include a reference to yet another model — for example, an logo image description in the database. Reviews depend on user accounts, which, in turn, might rely on some fundamental dictionaries like countries or languages, etc.

Note that it's all about purely business logic decisions, not about data structures. It's exactly what controllers are for in MVC paradigm — to unite distinct models in some sort of business process — for example, if you see the same product from buyer's point of view, you'll get page with reviews, cross-sales, etc. If you see the same product from supplier's POV, you'd be rather interested in sales data, etc — that is, a very different slice of information, obviously, with different last modification times.

And, in fact, controllers *already* do this job. In most caching-savvy controllers, there would some code like:

    @product = Product.find(id)
    @reviews = @product.reviews
    
    last_mod = ([@product.updated_at] + @reviews.map { |r| r.updated_at }).max
    
    if stale?(etag: [@product, @reviews],  last_modified: last_mod)
      # perform rendering
    end

Thus, controllers already contain the code to calculate last modification date for caching purposes — why don't we just call them and keep adhering to DRY principle?

Right now I'm using some code like that in `config/sitemap.rb`:

    app = ActionDispatch::Integration::Session.new Rails.application

    def add_with_lastmod(path)
      app.get path
      add path, lastmod: app.response.last_modified      
    end

    Content.find_each do |content|
      add_with_lastmod content_path(content)
    end

However, I'd prefer this code to be in the framework rather than copy-pasting it across all my projects. For that, I propose to add this special handling for some magic value like `:lastmod => :auto`. If you're not strongly opposing the idea, I can submit a pull request if you'd like to see it in action.

**Comment by kjvarga** [comment]
`last_mod = ([@product.updated_at] + @reviews.map { |r| r.updated_at }).max` IS ' just a method of a model'.    A url changes when the underlying data changes.  How you choose to access your data is up to you.  I suggest:

```ruby
# Product
class Product
  def most_recent_updated_at
    ([updated_at] + reviews.map(&:updated_at)).max
  end
end

# controller
if stale?(etag: [@product, @reviews],  last_modified:@product.most_recent_updated_at)
  # perform rendering
end

# sitemap
Content.find_each do |content|
  add content_path(content), lastmod: content.most_recent_updated_at
end
```

You most certainly DO NOT want to be rendering each URL and extracting any values from it.  That is upside-down logic.  Go bottom up.

**Comment by kjvarga** [comment]
If performance is a concern consider using a caching strategy for values like `most_recent_updated_at` and invalidate the cache when a product or review is updated.

**Comment by GreyCat** [comment]
It's definitely not a method of a model, at least unless you want to mirror all the representations from the controller. It's perfectly fine to have many distinct views on the same "product", for example:

* for the front-office — product page with lots of subpages, like:
  * main ecommerce product page (say, product + reviews)
  * "warehouses where product is available" page (product + warehouses)
  * "photo browser" (product + photos)
  * etc, etc.
* for the back-office:
  * product data editing page (product only)
  * supply chain information (product + supplies)
  * warehousing (product + warehouses + quantity of articles left)
  * photo catalogue (photos only)
  * etc, etc.

It's just crazy to add tons of model methods like:

```ruby
class Product
  def updated_at_when_on_main_front_page
    ([updated_at] + reviews.map(&:updated_at)).max
  end

  def updated_at_when_on_warehouses_front_page
    ([updated_at] + warehouses.map(&:updated_at)).max
  end

  def updated_at_when_on_photo_front_page
    ([updated_at] + photos.map(&:updated_at)).max
  end

  # ... zillions more, one per every controller method that renders a product-related page
end
```

It's *not* going upside-down, basically, it's just as good as querying the model — in both cases you basically just execute one method — either a method of model or a controller. Actual rendering of a resulting page in HTML is not required (although I admit my quickie 2-line implementation just asks for the whole cycle).

Afterall, when we're talking about sitemap, we're talking about URLs, i.e. actual pages that appear as a result of controller's work and may or may not be related to models. In fact, there could be no model at all: for example, a controller just queries some external web service and delivers results to view as is:

```ruby
class FeedController
  def index
    @feed = SomeExternalFeedAPIClient.query_stuff # returns JSON as Hash
    if stale?(etag: @feed, last_modified: @feed['last_modified'])
      # do the rendering
    end
  end
end
```

Would you propose to monkey-patch `SomeExternalFeedAPIClient` or wrap it in trivial model-like class?

**Comment by kjvarga** [comment]
In that case you can call your feed API from the sitemap generator.  I understand your problem.  This is now a philosophical discussion about where your code should live.  You're free to call a method on your controller if that's where your code lives.  You can do that in the sitemap generator.  But that's something you will have to add yourself.  I believe if you have business logic in a controller, move it to a lib or model or make it a class method...whatever allows it to be called externally.  There are many possible solutions to this problem, all with varying degrees of complexity.  A trivial solution would be to store/cache/update the product last_modified timestamp when any related model is modified.  Again, it's completely up to you.  I would advise to go with the simplest solution.
