### ISSUE TITLE
having trouble writing tests with rspec

### ISSUE THREAD

**Issue by lawhorkl** [kjvarga/sitemap_generator#229]
Hi!

I'm trying to integrate your gem into a curate-based application. The overall function of the gem is impeccable, I tried for a few days to find any errors in the generation, and I can't find any.

However, my problem is when I'm writing specs for the generator. 
(for reference, my branch is here: https://github.com/uclibs/scholar_uc/tree/enhancement/%23204-generate-sitemap-automatically , the sitemap.rb is in config/ and the sitemap_spec is in spec/features)

My problem currently is, I have objects in the database that are submitted by users, and I've written code to generate their links dynamically. 

My specific goal for the spec is to test these dynamic links by using the add method to add test objects  from the spec into the sitemap to be generated by the rake task. Is there any support for doing this with the sitemap_generator?

Thanks!

**Comment by kjvarga** [comment]
Sounds like in your case the best thing to do is to mock the `add` method and verify that it is called with the correct info to generate the links you expect.

Either that, or generate a sitemap file in the spec, then parse it with Nokogiri and verify contents that way.  

You can see quite a few examples in the `spec/` directory of the gem.
