### ISSUE TITLE
Error: both URI are relative

### ISSUE THREAD

**Issue by davidwessman** [kjvarga/sitemap_generator#230]
When trying to create sitemap on my staging server I get this:
```
URI::BadURIError: both URI are relative
.../sitemap_generator-5.1.0/lib/sitemap_generator/sitemap_location.rb:85:in `url'
.../sitemap_generator-5.1.0/lib/sitemap_generator/builder/sitemap_index_file.rb:143:in `write_first_sitemap'
.../sitemap_generator-5.1.0/lib/sitemap_generator/builder/sitemap_index_file.rb:104:in `finalize!'
.../sitemap_generator-5.1.0/lib/sitemap_generator/link_set.rb:461:in `finalize_sitemap_index!'
.../sitemap_generator-5.1.0/lib/sitemap_generator/link_set.rb:334:in `finalize!'
.../sitemap_generator-5.1.0/lib/sitemap_generator/link_set.rb:41:in `create'
.../sitemap_generator-5.1.0/lib/sitemap_generator.rb:42:in `method_missing'
.../config/sitemap.rb:5:in `run'
.../sitemap_generator-5.1.0/lib/sitemap_generator/interpreter.rb:76:in `instance_eval'
.../sitemap_generator-5.1.0/lib/sitemap_generator/interpreter.rb:76:in `run'
.../sitemap_generator-5.1.0/lib/sitemap_generator/tasks.rb:51:in `block (2 levels) in <top (required)>'
```

I set my `sitemaps_path = 'sitemaps/'`
No errors locally. Any clues?

**Comment by lawhorkl** [comment]
are you using a variable to dynamically set your application's url?

I ran into this problem with my application, so be sure that your url is set properly in sitemap.rb, use byebug to check its value.

**Comment by davidwessman** [comment]
Yeah, I wanted it to use based on my environment, anyway around this?

**Comment by lawhorkl** [comment]
Can you link to me how you set it? It's kinda hard to fix if I can't see what you did :p

**Comment by lawhorkl** [comment]
Also, try putting `puts default_host` right after the config line so that it will spit out the url's actual value after evaluating it, it could help ya figure out whats going on.

**Comment by davidwessman** [comment]
I used a constant set in the current environment and Rails should be properly loaded.

Locally it `puts` as the right value. Gonna try on the staging server.

**Comment by davidwessman** [comment]
When setting my `default_host` to include `http://` or `https://` it appears to work.
