### ISSUE TITLE
run sitemap update by sidekiq

### ISSUE THREAD

**Issue by leochulc** [kjvarga/sitemap_generator#231]
Sitemap_generator provide a tools to update sitemap by using `rake sitemap:refresh` . Is it possible by update it by sidekiq, which not suppose to use rake?

Leo

**Comment by leochulc** [comment]
[reply from Karl]

> Within your worker you can call `SitemapGenerator::Interpreter.run` and that will kick off sitemap creation, assuming your config file is in the default location.  If not you can pass the config file loc as an option.  Let me know if you have any trouble with the fact that Sidekiq runs jobs within the same rails env.  There shouldn't be an issue but someone else reported they had an issue.

Thanks, it works!

**Comment by samssouza** [comment]
Thank you i was looking for this! Would be great if that were in the docs as well
