### ISSUE TITLE
Turn of auto pinging when sitemap is hostet on AWS/S3

### ISSUE THREAD

**Issue by alereisan** [kjvarga/sitemap_generator#232]
Adding a redirect route in route.rb to the sitemap which is hosted on S3:

`get '/sitemap.xml.gz', to: redirect("https://#{ENV['S3_BUCKET_NAME']}.s3.amazonaws.com/sitemaps/sitemap.xml.gz"), as: :sitemap`

Maybe add this to the readme, because it makes it unnecessary to submit the s3 bucket url in google webmaster tools; makes it possible to directly submit `/sitemap.xml.gz` in google webmaster tools for the right domain, and also in robots.txt file, like: `Sitemap: https://www.domain.com/sitemap.xml.gz`
instead of `Sitemap: https://yourbucket.s3.amazonaws.com/sitemaps/sitemap.xml.gz`

But how can I turn of the pinging of my S3 bucket URL when i run `heroku run rake sitemap:refresh`?

I have added `SitemapGenerator::Sitemap.ping_search_engines('https://www.domain.com/sitemap.xml.gz')` at the bottom of sitemap.rb - which works - but it sends also pings with my S3 bucket url. Which is unclean IMO. How to turn this off?

**Comment by jphager2** [comment]
I think in this case you could just create your own task that loads `config/sitemap.rb` and then calls `SitemapGenerator::Sitemap.ping_search_engines(...)`

**Comment by kjvarga** [comment]
Run `heroku run rake sitemap:refresh:no_ping` to turn off the default ping.  Keep your manual ping and all will be well.

That is a nice clean redirect, but unfortunately you still need to verify ownership of the S3 bucket to in Google Webmaster tools when the root URLs of your sitemap do not match the host they are hosted on.  So I see no material benefit.
