### ISSUE TITLE
sitemap creating elements for all controllers and all actions

### ISSUE THREAD

**Issue by cheeby** [kjvarga/sitemap_generator#233]
Hi,

I've inherited a rails app that uses this gem. I really like what I see. But how can exclude certain controllers and actions? e.g., 

`<url>
<loc>http://www.example.com/organizations/new</loc>
<lastmod>2016-03-22T23:20:17-05:00</lastmod>
<changefreq>weekly</changefreq>
<priority>0.5</priority>
</url>`

and

`<url>
<loc>http://www.example.com/pictures/:id/edit</loc>
<lastmod>2016-03-22T23:20:17-05:00</lastmod>
<changefreq>weekly</changefreq>
<priority>0.5</priority>
</url>`

search engines don't need to know about edit, new, destroy, nor certain controllers that are there for back-end purposes like file_attachments or batch_action or /admin, /login.

Also, what shows up in the xml is a snippet like 

`<url>
<loc>http://www.example.com/products/:id</loc>
<lastmod>2016-03-22T23:20:17-05:00</lastmod>
<changefreq>weekly</changefreq>
<priority>0.5</priority>
</url>`

but what I'd like to see is not the route but rather the actual url of the product in there

`<url>
<loc>http://www.example.com/products/really-cool-rails-gem</loc>
<lastmod>2016-03-22T23:20:17-05:00</lastmod>
<changefreq>weekly</changefreq>
<priority>0.5</priority>
</url>
`
Thanks.

Steve

**Comment by kjvarga** [comment]
Only the URLs that you add to the sitemap are included, so the solution is not to add the ones you don't want :P  What's your sitemap config?
