### ISSUE TITLE
 No route matches [GET] "/sitemap.xml.gz"

### ISSUE THREAD

**Issue by marwenB** [kjvarga/sitemap_generator#234]
After i generated the sitemap, this error appear to me. 
 No route matches [GET] "/sitemap.xml.gz"
Can I get help please ?

**Comment by jphager2** [comment]
Is the file in your public folder? In your config, do you set a `sitemaps_path`, `public_path` or `filename`? What `adapter` do you set in your config?

**Comment by kjvarga** [comment]
Looks like you're not configured correctly to serve assets in public folder.  You can find more information on the web and ruby tutorials.

**Comment by Tioneb12** [comment]
config.public_file_server.enabled = true don't solve the problem for me.

I always get the same error : ActionController::RoutingError (No route matches [GET] "/sitemap.xml.gz")
