### ISSUE TITLE
Ensure sitemaps_host ends in /

### ISSUE THREAD

**Issue by jphager2** [kjvarga/sitemap_generator#236]
Hello,

I think that sitemap_host should also be ensured to end in /. Similar to how it is done [here](https://github.com/kjvarga/sitemap_generator/blob/master/lib/sitemap_generator/sitemap_location.rb#L21).

Otherwise URI.join creates doesn't work as expected (if / is missing)

Alternatively, it could be added to the docs that `sitemaps_host` should end in a /.

Best,
John

**Comment by kjvarga** [comment]
Thanks.  Want to submit a pull request? ;)

**Comment by jphager2** [comment]
Ok made a PR. Build is failing, though :(.

**Comment by kjvarga** [comment]
Hi @jphager2 sorry for not responding for so long.  I'm missing emails from this project...I have to check my filters.  What problem were you encountering?

It works when the host doesn't end in a slash....
```
irb(main):993:0> URI.join('http://host.com', 'path', 'file.txt')
=> #<URI::HTTP:0x007fd6f411d9d8 URL:http://host.com/file.txt>
```

Where are you having a problem?

**Comment by jphager2** [comment]
So the original case where I have the problem was when assigning 'http://www.example.com/something' to the `sitemap_host` Now it's obvious to me that this is wrong semantically and that I should append 'something' to the `sitemap_path`.
