### ISSUE TITLE
zip sitemap file

### ISSUE THREAD

**Issue by nikhil88877** [kjvarga/sitemap_generator#237]
I created the sitemap.xml.gz file in public folder by running - rake sitemap:refresh:no_ping
However, When I submit www.example.com/sitemap.xml.gz  in google webmaster, it gave 
General HTTP error: 404 not found
HTTP Error: 404
However, sitemap.xml.gz file is there in public folder and when access the url in browser, it simply downloads it.
Question- Can we submit zip file in google webmaster or not? If yes, then what am I doing wrong here?

**Comment by kjvarga** [comment]
Google cannot find the file.  As far as I'm aware they handle Gzipped files no problem, and you would have gotten a different error if they did not.

What's the URL of the sitemap file?
