### ISSUE TITLE
Builder versus Nokogiri::XML::Builder

### ISSUE THREAD

**Issue by mariusbutuc** [kjvarga/sitemap_generator#238]
The `sitemap_generator` gem depends on both [the `builder` gem](https://github.com/jimweirich/builder) and on [the `nokogiri` gem](https://github.com/sparklemotion/nokogiri). 

`nokogiri` comes with a `Nokogiri::XML::Builder`. @kjvarga, is there a specific reason why this is not used instead of `Builder::XmlMarkup`?

**Comment by kjvarga** [comment]
`sitemap_generator` only depends on the `builder` gem.  `nokogiri` is used in development only.
