### ISSUE TITLE
Multiple sitemaps within one index

### ISSUE THREAD

**Issue by jvvlee** [kjvarga/sitemap_generator#240]
I'm trying to build multiple sitemaps all listed under one index. The groups syntax seems to do this for me but if I were to generate this, I'd be forced to regenerate entire sitemaps that refer to content that never changes. Is there a way to individually regenerate sitemaps while still keeping them in one index file and appropriately updating their moddate?

**Comment by kjvarga** [comment]
There's no automatic way to do this.  However you can do it by separating the creation of the index and the sitemaps.  You would, for example, build/refresh individual sitemaps, then read the list of sitemaps and their file lastmod timestamps and regenerate the index.  You'd have to get into the internals of the package to do that, but it's not super hard.

**Comment by kjvarga** [comment]
Take a look at the `add_to_index` method.  This allows you to add links to the index directly.

"Sometimes you may need to manually add some links to the sitemap index file.  For example if you are generating your sitemaps incrementally you may want to create a sitemap index which includes the files which have already been generated.  To achieve this you can use the `add_to_index` method which works exactly the same as the `add` method described above."
