### ISSUE TITLE
Elastic Beanstalk writable directory

### ISSUE THREAD

**Issue by jgoodall628** [kjvarga/sitemap_generator#244]
Hello,
I am using elastic beanstalk in order to host my website. I have set up the sitemap generator to write the sitemaps to s3 but I cannot find a directory with write access in order to write out the temporary files. Does anyone know of a file in elastic beanstalk with write access? Any help is appreciated.

**Comment by kjvarga** [comment]
Have you tried accessing `/tmp`?

This might help: http://stackoverflow.com/questions/18184364/elastic-beanstalk-cron-and-deployment-permissions

**Comment by jgoodall628** [comment]
Thank you. The issue I was running into was you only choose to run the rake task or call it through a controller. I tested it using the rake task which is run as the ec2-user but the application uses the user webapp. So when I tried to modify the /tmp files my application didn't have ownership so it wouldn't allow me to update them. Once I deleted the files in /tmp and recreated them using the controller it worked.
