### ISSUE TITLE
Google doesn't support geo site maps anymore

### ISSUE THREAD

**Issue by mooreds** [kjvarga/sitemap_generator#246]
Since 2012, at least according to this: https://www.seroundtable.com/geo-sitemaps-gone-14941.html

Unclear if Bing supports it, but a quick search didn't turn up an authoritative answer.

The link in the docs to the geo sitemap example from Google also 404s.

**Comment by kjvarga** [comment]
Thanks for the heads-up

**Comment by kjvarga** [comment]
Released in v5.3.0
