### ISSUE TITLE
Support for Sitemap updates

### ISSUE THREAD

**Issue by jogaco** [kjvarga/sitemap_generator#247]
I have a site with over 2.6M pages.
I generated a sitemap with about 2.5M entries.
Mi site has about 50K new pages every week.
The sitemap protocol specifies here [http://www.sitemaps.org/faq.html#faq_submitting_changes](url) that in these cases, one should generate a small number of Sitemap files and use the lastmod field in the main Sitemap file to indicate the new pages.

Is this scenario supported?

**Comment by jogaco** [comment]
I've quickly written a script to solve the problem

**Comment by kjvarga** [comment]
Wow, that's pretty cool.  Unfortunately there is no built-in way to do what you want, so your hack was necessary.
