### ISSUE TITLE
Add adapter for writing to request

### ISSUE THREAD

**Issue by mooreds** [kjvarga/sitemap_generator#248]
For smallish sites, it might make sense to just output to stdout/the request, rather than to a file.  Then view caching could be used.

**Comment by kjvarga** [comment]
This does make sense.  It would only work for a site with < 50k links (i.e. doesn't require an index).  There's an easy way to achieve this:

```
SitemapGenerator::Sitemap.verbose = false
class SitemapGenerator::FileAdapter
  def write(location, raw_data)
    puts raw_data
  end
end
```

Would it be more helpful to have e.g. a `StreamAdapter` class that one could set the output stream on (file/stodout/whatever) and it writes to that?

**Comment by kjvarga** [comment]
I'm open to submissions, but I'm taking the project to maintenance mode.
