### ISSUE TITLE
Set lastmod of a group

### ISSUE THREAD

**Issue by loureirorg** [kjvarga/sitemap_generator#252]
Is it possible to set a "lastmod" on groups?

Example:

```
group(filename: "my_group", lastmod: "2016-10-28") do
...
end
```

**Comment by kjvarga** [comment]
Sorry for the delay.  You can't pass `lastmod` in the call to `groups` but rather just apply it to each link added within the group, e.g.

```
group(filename: 'my_group') do
  lastmod = "2016-10-28"
  add('/home', lastmod: lastmod)
end
```
