### ISSUE TITLE
Sitemaps for Multidomains

### ISSUE THREAD

**Issue by krtschmr** [kjvarga/sitemap_generator#253]
So we have a multi domain environment where each hosted website has basically the same routes
`category_path`, `mod_path` & `root_path`. 
Based on the domain constraint and other defaults, those links can change a little bit. 

`domain1.com/my-cool-game/special-cool/vehicles`
can be on a nother domain
`domain2.com/vehicles`

```
constraints DomainRouting.new("somethingdomain.com") do
    devise_for :users, controllers: { registrations: "registrations" }
    scope "mods" do
      defaults game: "some-game" do
        get "/*permalink",  to: "mods#show",       as: :mod, constraints: ModConstraint.new(:something)
        get "/*permalink",  to: "categories#show", as: :category, constraints: CategoryConstraint.new(:something)> 
      end
      root to: "categories#index"
    end
    get "/", to: redirect("/mods")
  end
```

the question here is, how to use this beautiful gem, or better to say, how to add the correct path since we don't have a request and i can't throw the constraints into the routing_paths ?

    SitemapGenerator::Sitemap.default_host = "http://www.#{public_domain}"
    SitemapGenerator::Sitemap.sitemaps_path = "sitemaps/#{code}"

so i would like to generate the sitemap for each website (`Website.first.create_sitemap`), so we set up the config, that works fine, but we struggle to get the right things generated

    cats.each do |category|
        add category_path(category), changefreq: :daily, priority: 0.9
      end

anybody had such an issue before?

**Comment by krtschmr** [comment]
i've ended up writing own helpers and then just `add mod_path(mod)` for each website. the helper is doing some prefixes for the routing. easiest solution i guess.

**Comment by kjvarga** [comment]
Glad you sorted it out.  Sorry I didn't reply earlier.

Seems like a decent solution.  I don't know the details of your setup, but your constraint classes could be used to return the path, if you add a method to the class that takes the domain (or whatever else it is that determines which path you return when) and returns the path.
