### ISSUE TITLE
What is best way, schema and sitemapa.

### ISSUE THREAD

**Issue by adrianoresende** [kjvarga/sitemap_generator#254]
Hello people,
I'm not sure what the best way to do schema and sitemapa is, check my questions.

First question: does the schema work inside the sitemap?
For example, after <loc> </ loc> you put <product> ... </ product>, without having to put microdata in HTML.

Second question: Is there a problem if I put a hash address 'http://foo.com/#termos' in sitemapa? Because the content is in the modal that opens automatically.

**Comment by kjvarga** [comment]
I don't understand your first question.  But generally this is the only valid XML that can appear in a sitemap if you are generating regular sitemaps: https://www.sitemaps.org/protocol.html

As for the second Q, no you shouldn't include named anchors in the URL.  Sitemap URLs should end with a slash `/` and identify a page, not a section of a page.

**Comment by adrianoresende** [comment]
I update comment:

`<loc> </ loc>` you put `<product> id, name, etc... </ product>`

**Comment by kjvarga** [comment]
No you can't have any non-standard XML in the sitemap file.  Why would you?  A sitemap parser wouldn't know what to do with it.

**Comment by kjvarga** [comment]
Your sitemaps will not validate and will not be accepted by search engines if they don't meet the specification I linked to in my original reply.
