### ISSUE TITLE
Ignore root

### ISSUE THREAD

**Issue by iamdriz** [kjvarga/sitemap_generator#255]
Is it possible to ignore the root? As I have built a CMS in Rails and the root is in fact a `Page`.

I don't want to ignore the `Page` for `/` as it has it's own last modfied, etc.

e.g.

~~~
Page.find_each do |page|
  add page.permalink, lastmod: page.updated_at
end
~~~

**Comment by kjvarga** [comment]
Sorry for the delay.  Set the `include_root` option to `false`.  https://github.com/kjvarga/sitemap_generator#sitemap-options

This can be set on `SitemapGenerator::Sitemap` or passed as options to `create`
