### ISSUE TITLE
Getting SitemapGenerator::SitemapFinalizedError when building sitemap from sidekiq job

### ISSUE THREAD

**Issue by fabn** [kjvarga/sitemap_generator#256]
I generate my sitemaps using a sidekiq job I've written, code is pretty simple and resemble the rake task provided with this gem

```ruby
  def generate_sitemap(type, site)
    api = WordpressAPI.new(site)
    config_path = "config/sitemaps/#{[type, 'sitemap'].compact.join('_')}.rb"
    logger.debug "Generating sitemap at #{sitemap_url(type)} with config file '#{config_path}'"
    # pick a namespace within your bucket when non in production
    final_path = ''.tap do |path|
      path << "#{Rails.env}/" unless Rails.env.production?
      path << "#{api.locale}/"
    end
    # Generate the sitemap with computed options
    SitemapGenerator::Interpreter.run config_file: config_path, default_host: api.homepage,
                                      current_site: api, yield_sitemap: true, sitemaps_path: final_path
  end
```

I'm generating a sitemap for another site, so I'm using a wrapper class to enumerate all articles I need (the `WordpressAPI` class above) and I pass it to generator using this monkey patch

```ruby
SitemapGenerator::LinkSet.instance_eval { attr_accessor :current_site }
```

Here's a simplified code that generate the sitemap

```ruby
SitemapGenerator::Sitemap.create namer: SitemapGenerator::SimpleNamer.new(:sitemap) do |sm|
  # Retrieve passed site
  site = sm.current_site
  # Check for for its presence and validity
  raise ArgumentError, "Missing or wrong site value: #{site.inspect}" unless site.presence.is_a?(WordpressAPI)

  add '/', changefreq: 'always', priority: 1

  # Iterates all posts and add a link for each of them
  site.posts(fields: %i(ID featured_image URL modified)).each do |post|
    begin
      last_edit = Time.parse(post[:modified])
      # Build options for this entry
      options = {lastmod: last_edit, changefreq: 'weekly'}
      options[:images] = [{loc: post[:featured_image]}] if post[:featured_image].present?
      options[:mobile] = true
      # Add the entry in the sitemap
      add post[:URL], options
    rescue => e
      # Do not stop sitemap generation if an error occur for a single entry
      Rollbar.warning 'Error while adding entry to sitemap', e, post
    end
  end
end
```

Each sitemap contains about 18000-25000 links.

Everything works when running the code from a rails console, both in production and in development, however when I run the code from sidekiq job in production (the app is running on heroku) sometimes I get a failure with `SitemapGenerator::SitemapFinalizedError` with this stacktrace

```
File "/app/vendor/bundle/ruby/2.3.0/gems/sitemap_generator-5.2.0/lib/sitemap_generator/builder/sitemap_file.rb" line 93 in add
File "/app/vendor/bundle/ruby/2.3.0/gems/sitemap_generator-5.2.0/lib/sitemap_generator/builder/sitemap_index_file.rb" line 67 in add
File "/app/vendor/bundle/ruby/2.3.0/gems/sitemap_generator-5.2.0/lib/sitemap_generator/link_set.rb" line 162 in add_to_index
File "/app/vendor/bundle/ruby/2.3.0/gems/sitemap_generator-5.2.0/lib/sitemap_generator/link_set.rb" line 454 in finalize_sitemap!
File "/app/vendor/bundle/ruby/2.3.0/gems/sitemap_generator-5.2.0/lib/sitemap_generator/link_set.rb" line 333 in finalize!
File "/app/vendor/bundle/ruby/2.3.0/gems/sitemap_generator-5.2.0/lib/sitemap_generator/link_set.rb" line 41 in create
File "/app/vendor/bundle/ruby/2.3.0/gems/sitemap_generator-5.2.0/lib/sitemap_generator.rb" line 42 in method_missing
File "config/sitemaps/sitemap.rb" line 1 in run
```

I'm using `AwsSdkAdapter` to upload the sitemap to S3.

The error doesn't always happen, I'm generating sitemap for 7 sites with this approach and 2 of them are working, the other get this behavior.

How can I fix this?

**Comment by fabn** [comment]
I'll found out that the issue is caused by this gem not being thread safe and not by sidekiq itself.

I've used the sidekiq approach to parallelize sitemap generation since I need to generate it for multiple sites. When I run a single job everything works like a charm, however when I run all jobs within sidekiq (so same process but different threads) I get the above error. Also I've inspected the generated sitemap when they are created in parallel they present mixed content e.g. link for a site are written to another sitemap possibly using default host for another one.

All these thing lead me to the conclusion that this gem uses shared stuff and it cannot be used in different threads.

I'll try to rewrite my code using [this approach](https://github.com/kjvarga/sitemap_generator#generating-multiple-sitemaps) and I will likely solve my issue.

I think you should put a big warning in the home page of the project to warn users to not use my approach because it will fail and it will fail badly...

**Comment by lfv89** [comment]
I'm having the exactly same problem trying to break the sitemap generation into different and parallel jobs... So, I can confirm, this can't be done since this gem is not thread safe.

**Comment by kjvarga** [comment]
@fabn and @lfv89 you're running into this problem because you're unwittingly using the same class instance in your parallel jobs.  This is because `SitemapGenerator::Sitemap` is actually a shared instance of the `LinkSet` class.  This is done to present a simplified API for general usage.

So your parallel jobs are using the same LinkSet instance and obviously trying to add links to a sitemap which has already been written out.

You need to modify your sitemap configuration to create a new LinkSet instance and use that anyplace you used `SitemapGenerator::Sitemap` previously. e.g.

```ruby
sitemap = SitemapGenerator::LinkSet.new
sitemap.default_host = 'http://foo.com'
...
```

or just pass options in constructor: `LinkSet.new(default_host: 'http://foo.com', ...)`

**Comment by fabn** [comment]
@kjvarga thanks, I'm trying your suggestion right now and it seems to work.
