### ISSUE TITLE
Disable changefreq and priority

### ISSUE THREAD

**Issue by Brotakuu** [kjvarga/sitemap_generator#257]
Is it possible to disable the two optional parameters?

`rake -s sitemap:refresh` doesnt do the trick.

**Comment by kjvarga** [comment]
Yes you can disable these two options.  Pass a value of `nil` for these options with each call to `add` e.g. `add('/url', changefreq: nil, priority: nil)`.

**Comment by kjvarga** [comment]
@jacek213 see #313
