### ISSUE TITLE
As a View?

### ISSUE THREAD

**Issue by tiagoovieira** [kjvarga/sitemap_generator#261]
I tried the upload to S3, successfully, but on google webmaster tools I can't add the sitemap. I tried to add a controller method to redirect the path /sitemap.xml to the s3 url, reverse proxy it, none with success. Is it possible to use this in a view, generating the xml when /sitemap.xml is requested?

**Comment by kjvarga** [comment]
You have to prove to Google that you own the S3 bucket.  Take a look at Step 4 here: https://github.com/kjvarga/sitemap_generator#upload-sitemaps-to-a-remote-host-using-adapters

I think that will solve your problem.  It is possible to dynamically generate the XML but unadvisable for a site of any size.

**Comment by kjvarga** [comment]
You might find this helpful too: https://github.com/kjvarga/sitemap_generator/issues/248

**Comment by januszm** [comment]
You'll see an error in Google if the urls inside the generated sitemap don't match the domain where the sitemap.xml file is hosted. This is the case when you upload the sitemap to S3. I'd recommend to  set up the S3 bucket for Web Site Hosting and add a subdomain, like `sitemap....` that points to that S3 bucket.

**Comment by jakeonrails** [comment]
Our current implementation before using sitemap_generator (we are porting over right now) is to do something like this:

```ruby
  # GET /sitemap.xml
  def index
    render inline: read_from_s3('sitemap.xml')
  end

private
  def read_from_s3(filename)
    s3 = Aws::S3::Client.new
    object = s3.get_object(
      bucket: AWS_CONFIG[:sitemaps_bucket],
      key: "#{ AWS_CONFIG[:sitemaps_path] }/#{ filename }.xml"
    )
    object.body.read
  end
```

So this means setting up a Rails controller, adding index and show methods, (index = sitemap index, show = individual sitemaps), and then proxying to AWS through the controller action. Obviously this isn't optimal for performance, but on Heroku it seems the only reasonable way to get the performance we need.

Finally there's another option, and if the size of your sitemaps is small it may be feasible. On Heroku there is a buildpack that can trigger rake actions immediately before your deploy finishes. One use case is to automatically run rake db:migrate, but we could use this to run the sitemap generator to write the sitemaps to the `/public` directory right before deploy, and that way each dyno would have an updated sitemap in the public directory ready to serve to google. The downside to this is if you do not deploy frequently your sitemaps become stale. I prefer the proxied method described above. [The buildpack is here](https://github.com/gunpowderlabs/buildpack-ruby-rake-deploy-tasks)

One final method I just thought of is to use a liteweight nginx proxy buildpack in front of your Rails app on heroku, and have it `proxy_pass` any sitemaps requests on to your S3 bucket.

**Comment by kjvarga** [comment]
That's neat if you can generate the sitemap before your deploy on Heroku.  But you still have the problem of stale sitemaps between deploys.

By far the simplest setup is to generate the sitemaps periodically and upload to S3.  Have your robots.txt point to S3 and prove ownership of the S3 bucket.  This allows the URLs in the sitemaps to differ from the domain on which they are hosted (S3).

https://github.com/kjvarga/sitemap_generator#an-example-of-using-an-adapter
