### ISSUE TITLE
5.3.0 is not starting

### ISSUE THREAD

**Issue by karensg** [kjvarga/sitemap_generator#264]
Hi,

Not sure if I am doing something wrong, but after the update, the library suddenly stopped working. The whole Rails application can't start any more (on AWS EC2). Any ideas?

```
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- sitemap_generator/builder (LoadError)
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/sitemap_generator-5.3.0/lib/sitemap_generator.rb:2:in `<top (required)>'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.1/lib/bundler/runtime.rb:86:in `require'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.1/lib/bundler/runtime.rb:86:in `block (2 levels) in require'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.1/lib/bundler/runtime.rb:81:in `each'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.1/lib/bundler/runtime.rb:81:in `block in require'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.1/lib/bundler/runtime.rb:70:in `each'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.1/lib/bundler/runtime.rb:70:in `require'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.1/lib/bundler.rb:102:in `require'
	from /var/app/current/config/application.rb:7:in `<top (required)>'
	from /var/app/current/config/environment.rb:2:in `require'
	from /var/app/current/config/environment.rb:2:in `<top (required)>'
```

**Comment by kjvarga** [comment]
Hi Karens, I'm not able to reproduce.  Can you show me your sitemap config and let me know how you are running it (via rake task or otherwise)?

Looks like you're using Ruby 2.3.1, rubygems 2.3.0 and Rails 4.2.8.  That right?

And in your Gemfile you have a line like `gem 'sitemap_generator'`?

**Comment by kjvarga** [comment]
I can see no reason why that `require` would fail, since that hasn't changed and the builder file is part of the gem bundle.  As a basic check could you do the following:

(You'll probably have to `gem install sitemap_generator`)

```shell
$ irb
irb(main):001:0> require 'rubygems'
=> false
irb(main):002:0> require 'sitemap_generator'
=> true
irb(main):004:0> SitemapGenerator::Builder
=> SitemapGenerator::Builder
```

**Comment by karensg** [comment]
Hi, 
Ruby 2.3.1, rubygems 2.3.0 and Rails 4.2.8 is indeed my setup.

I have a job which runs in the background:
```ruby
SitemapGenerator::Interpreter.run
SitemapGenerator::Sitemap.ping_search_engines
```
Then this is my config
```ruby
  SitemapGenerator::Sitemap.default_host = ...
  SitemapGenerator::Sitemap.compress = false
  SitemapGenerator::Sitemap.public_path = 'tmp'
  SitemapGenerator::Sitemap.adapter = SitemapGenerator::AwsSdkAdapter.new('...', path: '')
  SitemapGenerator::Sitemap.create do
     ...
  end
```
My gemfile is just
```
gem 'sitemap_generator'
```

I do not have this anywhere. It was not necessary before.
```
require 'rubygems'
require 'sitemap_generator'
```

**Comment by kjvarga** [comment]
Thanks for the info.

This code ```require 'rubygems'
require 'sitemap_generator'``` is only needed because I was using IRB and not the Rails console.

**Comment by kjvarga** [comment]
I wonder if the gem didn't install properly for you.  I setup an environment similar to yours and have no problem generating sitemaps, running rake or starting rails.

**Comment by inyerade** [comment]
Same error in installation.

    bundle install -----> Installing sitemap_generator 5.3.0
    rake sitemap:install  --------> ERROR


    /var/lib/gems/2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- sitemap_generator/builder (LoadError)
	from /var/lib/gems/2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
	from /var/lib/gems/2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /var/lib/gems/2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /var/lib/gems/2.3.0/gems/sitemap_generator-5.3.0/lib/sitemap_generator.rb:2:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/bundler-1.12.1/lib/bundler/runtime.rb:86:in `require'
	from /var/lib/gems/2.3.0/gems/bundler-1.12.1/lib/bundler/runtime.rb:86:in `block (2 levels) in require'
	from /var/lib/gems/2.3.0/gems/bundler-1.12.1/lib/bundler/runtime.rb:81:in `each'
	from /var/lib/gems/2.3.0/gems/bundler-1.12.1/lib/bundler/runtime.rb:81:in `block in require'
	from /var/lib/gems/2.3.0/gems/bundler-1.12.1/lib/bundler/runtime.rb:70:in `each'
	from /var/lib/gems/2.3.0/gems/bundler-1.12.1/lib/bundler/runtime.rb:70:in `require'
	from /var/lib/gems/2.3.0/gems/bundler-1.12.1/lib/bundler.rb:102:in `require'
	from /home/inye/Escritorio/zembia/repos/primavera_rails/config/application.rb:7:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/spring-1.6.4/lib/spring/application.rb:82:in `require'
	from /var/lib/gems/2.3.0/gems/spring-1.6.4/lib/spring/application.rb:82:in `preload'
	from /var/lib/gems/2.3.0/gems/spring-1.6.4/lib/spring/application.rb:143:in `serve'
	from /var/lib/gems/2.3.0/gems/spring-1.6.4/lib/spring/application.rb:131:in `block in run'
	from /var/lib/gems/2.3.0/gems/spring-1.6.4/lib/spring/application.rb:125:in `loop'
	from /var/lib/gems/2.3.0/gems/spring-1.6.4/lib/spring/application.rb:125:in `run'
	from /var/lib/gems/2.3.0/gems/spring-1.6.4/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'

**Comment by kjvarga** [comment]
Rake will load your rails env so that's likely to fail given your problems.

Can you please 'gem uninstall' then 'gem install' the gem.  Then open 'irb'
and run the code I pasted above and let me know what happens.

**Comment by inyerade** [comment]
@kjvarga this you need?

```
irb          
irb(main):001:0> require 'rubygems'
=> false
irb(main):002:0> require 'sitemap_generator'
LoadError: cannot load such file -- sitemap_generator/builder
	from /var/lib/gems/2.3.0/gems/sitemap_generator-5.3.0/lib/sitemap_generator.rb:2:in `require'
	from /var/lib/gems/2.3.0/gems/sitemap_generator-5.3.0/lib/sitemap_generator.rb:2:in `<top (required)>'
	from (irb):2:in `require'
	from (irb):2
	from /usr/bin/irb:11:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/bundler-1.12.1/lib/bundler/cli/exec.rb:63:in `load'
	from /var/lib/gems/2.3.0/gems/bundler-1.12.1/lib/bundler/cli/exec.rb:63:in `kernel_load'
	from /var/lib/gems/2.3.0/gems/bundler-1.12.1/lib/bundler/cli/exec.rb:24:in `run'
	from /var/lib/gems/2.3.0/gems/bundler-1.12.1/lib/bundler/cli.rb:304:in `exec'
	from /var/lib/gems/2.3.0/gems/bundler-1.12.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/2.3.0/gems/bundler-1.12.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /var/lib/gems/2.3.0/gems/bundler-1.12.1/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
	from /var/lib/gems/2.3.0/gems/bundler-1.12.1/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
	from /var/lib/gems/2.3.0/gems/bundler-1.12.1/lib/bundler/cli.rb:11:in `start'
	from /var/lib/gems/2.3.0/gems/bundler-1.12.1/exe/bundle:27:in `block in <top (required)>'
	from /var/lib/gems/2.3.0/gems/bundler-1.12.1/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
	from /var/lib/gems/2.3.0/gems/bundler-1.12.1/exe/bundle:19:in `<top (required)>'
	from /usr/local/bin/bundle:23:in `load'
	from /usr/local/bin/bundle:23:in `<main>'

```

**Comment by kjvarga** [comment]
@inyerade I'm still not able to reproduce the error unfortunately.  Could you please take a look at the contents of the gem and make sure that the file `lib/sitemap_generator/builder.rb` is within the package and looks normal (it's required on line 2 of `lib/sitemap_generator.rb`.

To easily open the gem in your editor you can `gem install gemedit` and `gem edit sitemap_generator`

**Comment by kjvarga** [comment]
Or can you send me a zip of the gem contents?  kjvarga@gmail.com

**Comment by inyerade** [comment]
Full content of `lib/sitemap_generator/builder.rb`

```    
require 'sitemap_generator/builder/sitemap_file'
require 'sitemap_generator/builder/sitemap_index_file'
require 'sitemap_generator/builder/sitemap_url'
require 'sitemap_generator/builder/sitemap_index_url'

module SitemapGenerator::Builder
  LinkHolder = Struct.new(:link, :options)
end
```

**Comment by inyerade** [comment]
Add my app env
```
Rails version             4.2.5
Ruby version              2.3.1-p112 (x86_64-linux-gnu)
RubyGems version          2.5.1
Rack version              1.6.4
```

**Comment by kjvarga** [comment]
@inyerade have you tried uninstalling and reinstalling the gem?

The issue seems to do with the load path and it's hard to see that it's a problem with the gem itself since the file it's looking for is there.  Very weird.

**Comment by inyerade** [comment]
What is the process to unistall and reintall?

**Comment by cguyer** [comment]
also had an issues upgrading from 5.1.0 to 5.3.0 locked at 5.2.0 with no problems.
Rails 4.2.8
ruby 2.3.0p0

`Message from application: cannot load such file -- sitemap_generator/builder (LoadError)
  /export/home/site.org/project/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
  /export/home/site.org/project/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
  /export/home/site.org/project/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
  /export/home/site.org/project/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
  /export/home/site.org/project/shared/bundle/ruby/2.3.0/gems/sitemap_generator-5.3.0/lib/sitemap_generator.rb:2:in `<top (required)>'
  /usr/local/rvm/gems/ruby-2.3.0@global/gems/bundler-1.13.1/lib/bundler/runtime.rb:91:in `require'
  /usr/local/rvm/gems/ruby-2.3.0@global/gems/bundler-1.13.1/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
  /usr/local/rvm/gems/ruby-2.3.0@global/gems/bundler-1.13.1/lib/bundler/runtime.rb:86:in `each'
  /usr/local/rvm/gems/ruby-2.3.0@global/gems/bundler-1.13.1/lib/bundler/runtime.rb:86:in `block in require'
  /usr/local/rvm/gems/ruby-2.3.0@global/gems/bundler-1.13.1/lib/bundler/runtime.rb:75:in `each'
  /usr/local/rvm/gems/ruby-2.3.0@global/gems/bundler-1.13.1/lib/bundler/runtime.rb:75:in `require'
  /usr/local/rvm/gems/ruby-2.3.0@global/gems/bundler-1.13.1/lib/bundler.rb:106:in `require'
  /export/home/site.org/project/releases/20170222192808/config/application.rb:7:in `<top (required)>'
  /export/home/site.org/project/releases/20170222192808/config/environment.rb:2:in `require'
  /export/home/site.org/project/releases/20170222192808/config/environment.rb:2:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /export/home/site.org/project/shared/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:55:in `instance_eval'
  /export/home/site.org/project/shared/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'`

**Comment by kjvarga** [comment]
@inyerade `gem uninstall sitemap_generator` `gem install sitemap_generator`

**Comment by inyerade** [comment]
@kjvarga same problem.

With 5.2.0 I do not have problem.

**Comment by singler** [comment]
Hey, I had same problem as @karensg. In my setup code is executed by another user than the one who built the gem. It appears that build process makes some files to have 700 permissions due to which other users cannot read these files. doing "chmod -R a+r" solves the problem.

**Comment by kjvarga** [comment]
Thanks so much @singler for finding the issue!  I've rebuilt the gem after ensuring the file permissions are correct and pushed v5.3.1.  Could you please try that out and let me know if that solves the problem?

Turns out one of my machines has bad file permissions and I must have built the gem on this machine.  Unfortunately git doesn't keep track of these file permissions :(

**Comment by karensg** [comment]
Just updated to the new version. It all works proper now. Thanks a lot, @singler and @kjvarga,
