### ISSUE TITLE
Sitemap on AWS: permission denied error

### ISSUE THREAD

**Issue by davideghz** [kjvarga/sitemap_generator#265]
Trying to generate a sitemap on AWS, with `rake sitemap:refresh`.

Got this error:

```
rake aborted!
Errno::EACCES: Permission denied @ rb_sysopen - /var/app/current/public/sitemap.xml
/var/app/current/config/sitemap.rb:29:in `block in run'
/var/app/current/config/sitemap.rb:4:in `run'
Tasks: TOP => sitemap:refresh => sitemap:create
```

**Comment by davideghz** [comment]
solved with `sudo chmod 777 public` but I'm sure it's not the good way to handle it ..

**Comment by kjvarga** [comment]
Please see this thread: https://github.com/kjvarga/sitemap_generator/issues/264

**Comment by kjvarga** [comment]
Sorry your issue looks like it's different.  Your `public` directory needs to be writeable by the user that the runs the script to generate the sitemaps.  That's probably `ec-user` on AWS but I'm not sure of your setup.

**Comment by davideghz** [comment]
Thanks for the followup, you are correct about it (just the standard user's name on AWS is `ec2-user`).
