### ISSUE TITLE
sitemap & AWS EB loadbalancer

### ISSUE THREAD

**Issue by davideghz** [kjvarga/sitemap_generator#271]
When my app scale up and a new EC2 instance is generated, I lose the sitemap.
How do you manage this? Thanks

**Comment by kjvarga** [comment]
I'd suggest storing your sitemaps in S3.  Then having your robots.txt file point to that.  There's more info in the readme and the wiki about how to do that.

**Comment by davideghz** [comment]
hi @kjvarga thanks for your input. Anyway I don't understand why the sitemap got lost once a new EC2 spawns.. it's in the /public folder along with other resources - e.g, 404.html, robot.txt, etc.. - that does not disappear.

**Comment by kjvarga** [comment]
Usually the instance is built from your application bundle if you're using
Elastic Beanstalk.  Anything that isn't contained in the bundle is lost on
new instance startup.

**Comment by davideghz** [comment]
Okay, thanks, very clear
