### ISSUE TITLE
This url is not allowed for a Sitemap at this location

### ISSUE THREAD

**Issue by bufordtaylor** [kjvarga/sitemap_generator#272]
I've read through the docs but it doesn't appear the steps I'm following are working.

I'm creating a sitemap using the WaveAdapter and followed the steps directed: https://github.com/kjvarga/sitemap_generator/wiki/Generate-Sitemaps-on-read-only-filesystems-like-Heroku

- [x] In my s3 bucket, the sitemaps appear perfectly.
- [x] I've gone into google webmaster tools and verified that I own the s3 bucket
- [ ] When I go to submit the sitemap, I get errors: ![error1](https://i.imgur.com/uogob8v.png)

Clicking through the errors above, you can see that it's because the s3 bucket URL does not match the indexed pages: ![error2](https://i.imgur.com/1TdQK9g.png)

I thought, "okay, what if I go about it the other way?"

- [x] I went into google webmaster tools and verified I own the site
- [x] I added a redirect in my routes `  get "sitemap.xml" => redirect("http://s3.amazonaws.com/path/to/sitemap.xml.gz")`
- [ ] When I go to submit the sitemap, I get errors again: ![error3](https://i.imgur.com/bbFj6UR.png)

Clicking through the errors, it's pretty much the same issue: ![error4](https://i.imgur.com/jglAvA5.png)

How are people getting around this?

**Comment by kjvarga** [comment]
Have you done this step:

> To make sure that your sitemaps are found by the search engines, include
the link to the sitemap.xml.gz file in your robots.txt file, by adding a
line like the following:

Sitemap: http://s3.amazonaws.com/sitemap-generator/sitemaps/sitemap.xml.gz

If you've proved that you own the s3 bucket correctly then things should be
okay.

Did you set your sitemaps_host correctly?  It should be the S3 buck t
location.  It sounds like you have about a half million links so you
probably have a number of sitemaps with the first being the sitemaps
index.  Try generating without compression and verify the the index links
point to the correct locations on S3.  Google isn't complaining about not
finding th files, but can't hurt to double check.

Using a redirect won't help you in this scenario.  The only alternative is
to proxy the files by streaming them when a request is made to your
server.  But that isn't ideal cause it's slow and in this case you'd have
to change your sitemaps config before that would be accepted by google.
Bette to get it working as is.

**Comment by bufordtaylor** [comment]
I think I'm going to close this issue. Without changing anything, I woke up this morning and checked GWTs to find that Google started indexing the site ![pic](https://i.imgur.com/4H6k2Mg.png)

Thanks for the assist. I guess I just needed some patience.
