### ISSUE TITLE
Human readable stylesheets

### ISSUE THREAD

**Issue by mesge** [kjvarga/sitemap_generator#273]
I noticed there's no option to configure a stylesheet for generated sitemaps. Having a human-readable sitemap can often be useful for debugging (imagine you're not a developer and reading raw XML or ruby code is daunting). Is there any intention to add a feature like this to the roadmap? More than happy to help out with a PR if maintainers are interested.

**Comment by kjvarga** [comment]
There is an option to generate an uncompressed sitemap, is that not what
you're looking for?

**Comment by mesge** [comment]
Not exactly. For example, in the Wordpress ecosystem a plugin made by [Yoast](http://www.yoast.com) generates styled xml sitemaps with linkable locations. [Here's what it looks like](https://yoast.com/sitemap_index.xml).

A styled sitemap is a little easier to digest than the document tree shown by most browsers when the stylesheet isn't present. Can be handy to confirm that everything is in order.

**Comment by kjvarga** [comment]
Would the user would have to host their own stylesheet?  Or is there a public one we can use?

**Comment by kjvarga** [comment]
This isn't a priority for most people.  I'd consider including a stylesheet if it was hosted remotely and was reliable.
