### ISSUE TITLE
SiteMapGenerator with AwsSdkAdapter is improperly writing to local file.

### ISSUE THREAD

**Issue by lonny** [kjvarga/sitemap_generator#274]
We have a production application on Engine Yard, and our sitemaps on S3.

Recently, Engine Yard updated their deployment gem, and we were forced to update it or else our deploys were broken.

That update caused a cascade of other gems to be updated when bundle install was run. And since then we have been unable to get SiteMapGenerator working properly. Prior to this it was working fine.

SitemapGenerator itself was not updated. This is version 5.2.0.

Here is the setup portion of the code (domain name has been edited, otherwise verbatim):

```
## Comment this adapter below for testing in dev (local) mode. Sitemaps will be generated in public/system/sitemaps.
SitemapGenerator::Sitemap.adapter = SitemapGenerator::AwsSdkAdapter.new('sitemaps.propertynerd.com.au',
                                                                          :aws_access_key_id     => creds["AccessKeyId"],
                                                                          :aws_secret_access_key => creds["SecretAccessKey"],
                                                                          :aws_region            => creds["Region"],
                                                                          :path                  => "")
# SitemapGenerator::Sitemap.adapter = SitemapGenerator::FileAdapter.new                   ## Uncomment this for testing.
SitemapGenerator::Sitemap.compress      = false
SitemapGenerator::Sitemap.create_index  = true
SitemapGenerator::Sitemap.default_host  = "https://www.mysite.com"             ## Comment this for testing.
# SitemapGenerator::Sitemap.default_host  = "http://localhost:5000"                       ## Uncomment this for testing.
SitemapGenerator::Sitemap.sitemaps_host = "https://sitemaps.mysite.com"        ## Comment this for testing.
SitemapGenerator::Sitemap.sitemaps_path = 'system/sitemaps'
```

With this setup the files were being uploaded to S3 bucket "sitemaps.mysite.com/system/sitemaps".

But now it's writing the files to pubic/system/sitemaps, despite the fact that the AwsSdkAdapter is specified, and the FileAdapter is commented. We reverse that for testing, but only for testing.

Any ideas? This is a critical issue. Until we get this fixed our site will not be indexed properly.

If you need any further information do not hesitate to ask.

**Comment by kjvarga** [comment]
The `AwsSdkAdapter` writes each file to disk and then uploads it to S3.  I think at the time it wasn't possible to upload directly without writing, I can't recall.  So check S3, your sitemaps should be uploaded.  You can run the `rake sitemap:refresh --trace` task manually and look for any error output.  I think the aws-sdk gem doesn't have very good debug output.  But I suspect things are still working for you.

**Comment by lonny** [comment]
I have determined that it is not a problem with sitemap generator after all. In fact it was an issue with our system's ability to connect with S3.

Looking into that.  Pardon the false alarm. We really thought it was the sitemap generator because at first it appeared that everything else was working.
