### ISSUE TITLE
Sitemap file size limit handling

### ISSUE THREAD

**Issue by phlegx** [kjvarga/sitemap_generator#277]
Hi!

Is it possible to add file size limit handling? 
At the moment the constant `SitemapGenerator::MAX_SITEMAP_FILESIZE` is set to `10_000_000` (10 MB). But Google and Bing has changed the size to 50 MB.

1. http://searchengineland.com/google-bing-increase-file-size-limit-sitemaps-files-264338
2. http://stackoverflow.com/questions/2887358/limitation-for-google-sitemap-xml-file-size

For better handling with different search engines it should be good to add the ability to config:

- MAX_SITEMAP_FILES
- MAX_SITEMAP_LINKS
- MAX_SITEMAP_IMAGES
- MAX_SITEMAP_NEWS
- MAX_SITEMAP_FILESIZE

At the moment I re-set the constant in `config/initializers/sitemap.rb` with:

```ruby
Kernel::silence_warnings { SitemapGenerator::MAX_SITEMAP_FILESIZE = 50_000_000 }
```

**Comment by kjvarga** [comment]
Thanks for the heads-up.  I'll look at increasing that limit.  I wasn't aware that it changed.  I agree that it would be nice to be able to set it.  

You can set `max_sitemap_links` via config now.

**Comment by phlegx** [comment]
My opinion is, that all this parameters should be configurable because the rules are not the same for all search engines. Thx for your fast responses :laughing:
