### ISSUE TITLE
Sitemaps generating unexpected sitemaps path for AwsSdkAdapter

### ISSUE THREAD

**Issue by jfyzhao** [kjvarga/sitemap_generator#279]
I'm using the following settings with the AwsSdk Adapter for creating my stiemaps:
SitemapGenerator::Sitemap.default_host = "https://www.mysite.com"
SitemapGenerator::Sitemap.create_index = true
SitemapGenerator::Sitemap.sitemaps_host = "https://s3-us-west-2.amazonaws.com/mysite-assets/"
SitemapGenerator::Sitemap.sitemaps_path = "sitemaps/"
SitemapGenerator::Sitemap.adapter = SitemapGenerator::AwsSdkAdapter.new('mysite-assets')

However, this is generating the sitemaps in https://s3-us-west-2.amazonaws.com/mysite-assets/sitemaps/sitemaps/ so that there is an extra sitemaps/ subdirectory created. I can remove the   SitemapGenerator::Sitemap.sitemaps_path = "sitemaps/" line, but that causes the search engines to incorrectly ping for the sitemaps in https://s3-us-west-2.amazonaws.com/mysite-assets/ instead of https://s3-us-west-2.amazonaws.com/mysite-assets/sitemaps/

**Comment by kjvarga** [comment]
You're right, there's a bug in the `AwsSdkAdapter` code here https://github.com/kjvarga/sitemap_generator/blob/master/lib/sitemap_generator/adapters/aws_sdk_adapter.rb#L25

Can you try creating your adapter like so:
`SitemapGenerator::Sitemap.adapter = SitemapGenerator::AwsSdkAdapter.new('mysite-assets', :path => '')`

That should avoid the issue until I can fix it.

**Comment by jfyzhao** [comment]
Yup that fixed it! No worries, thanks for the suggestion.

**Comment by bwoodmansee** [comment]
:+1:

**Comment by kjvarga** [comment]
This is fixed in v6.0.0 of the gem, you can remove this workaround.
