### ISSUE TITLE
SitemapGenerator::WaveAdapter looking for generated sitemap in the wrong location

### ISSUE THREAD

**Issue by stevenmaguire** [kjvarga/sitemap_generator#292]
My config includes the following:

```
SitemapGenerator::Sitemap.adapter = SitemapGenerator::WaveAdapter.new
SitemapGenerator::Sitemap.public_path = 'tmp/'
SitemapGenerator::Sitemap.sitemaps_path = 'sitemaps/'
```

And I can see the sitemap being generated at `app/tmp/sitemaps/sitemap.xml.gz`

The console reports the following error: 

`Errno::ENOENT: No such file or directory @ rb_sysopen - /path/to/app/tmp/1505512322-22984-0001-8183/sitemap.xml.gz`

I would expect the upload process to look for the file at `/path/to/app/tmp/sitemaps/sitemap.xml.gz`

I am using version 5.3.1 of this gem.

Am I missing something?

**Comment by kjvarga** [comment]
Can you paste the full exception trace please (pass `--trace` if calling with `rake`).  I suspect that this issue is caused by CarrierWave itself trying to delete the file from "cache" when it DNE there.

Also, the latest version of CW is 1.1.0.  But you claim to have version 5.3.1?

**Comment by stevenmaguire** [comment]
I will get a full trace and report back. 

Regarding the version note, I am using 5.3.1 of THIS gem, `sitemap_generator`.

**Comment by kjvarga** [comment]
Just tested and this is working for me with latest CarrierWave.
