### ISSUE TITLE
NameError: uninitialized constant

### ISSUE THREAD

**Issue by nikanet** [kjvarga/sitemap_generator#301]
I try to run config from instruction, but get an error:

```
MacBook-Pro:myapp nikanet$ rake sitemap:refresh:no_ping
In '/Users/nikanet/myapp/public/':
rake aborted!
NameError: uninitialized constant #<Class:#<SitemapGenerator::Interpreter:0x007ff18b9d0560>>::Content
/Users/nikanet/myapp/config/sitemap.rb:29:in `block in run'
/Library/Ruby/Gems/2.3.0/gems/sitemap_generator-6.0.1/lib/sitemap_generator/interpreter.rb:61:in `instance_eval'
/Library/Ruby/Gems/2.3.0/gems/sitemap_generator-6.0.1/lib/sitemap_generator/interpreter.rb:61:in `eval'
/Library/Ruby/Gems/2.3.0/gems/sitemap_generator-6.0.1/lib/sitemap_generator/link_set.rb:40:in `create'
/Library/Ruby/Gems/2.3.0/gems/sitemap_generator-6.0.1/lib/sitemap_generator.rb:41:in `method_missing'
/Users/nikanet/myapp/config/sitemap.rb:4:in `run'
/Library/Ruby/Gems/2.3.0/gems/sitemap_generator-6.0.1/lib/sitemap_generator/interpreter.rb:78:in `instance_eval'
/Library/Ruby/Gems/2.3.0/gems/sitemap_generator-6.0.1/lib/sitemap_generator/interpreter.rb:78:in `run'
/Library/Ruby/Gems/2.3.0/gems/sitemap_generator-6.0.1/lib/sitemap_generator/tasks.rb:51:in `block (2 levels) in <top (required)>'
/Library/Ruby/Gems/2.3.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => sitemap:refresh:no_ping => sitemap:create
(See full trace by running task with --trace)
```

My config file (sitemap.rb):

```
# Set the host name for URL creation
SitemapGenerator::Sitemap.default_host = "http://www.example.com"

SitemapGenerator::Sitemap.create do

  add '/contact_us'
  Content.find_each do |content|
    add content_path(content), :lastmod => content.updated_at
  end

end
```

Rakefile:

```
# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require 'rubygems'
require 'sitemap_generator/tasks'
require_relative 'config/application'


Rails.application.load_tasks

```
I'm beginner. Please help.

**Comment by kjvarga** [comment]
It's not able to resolve the `Content` class.  Are you running this inside Rails?  If so, the rake tasks are included automatically for you and you don't need to add anything to the rake file.  Make sure you have defined a `Content` model.

**Comment by nikanet** [comment]
How define model and how run script inside Rails?

**Comment by kjvarga** [comment]
You asked: "How define model and how run script inside Rails?"

You're going to have to read up on Ruby on Rails.  There are plenty of guides that will help you to create a model and get setup.

Just delete 
```Content.find_each do |content|
    add content_path(content), :lastmod => content.updated_at
  end
```
from your sitemap config file.

And remove `require 'sitemap_generator/tasks'` from your rakefile.

Then run `rake sitemap:refresh:no_ping` and things should work for you.

**Comment by nikanet** [comment]
It's work. But i want to generate sitemap for all pages of site. How do this?

**Comment by kjvarga** [comment]
Please check the README.  You can add links like `add '/contact_us'`.  Just change the link to whatever you want.  If you want to use data from a database you'll need to define a model and use that.  But you're going to have to learn how to do that yourself.

This is a test app that I use for testing the sitemap generator: https://github.com/kjvarga/sitemap_generator-test/blob/rails4.2.8/app/models/content.rb

**Comment by nikanet** [comment]
Thank you!
