### ISSUE TITLE
Defining model

### ISSUE THREAD

**Issue by nikanet** [kjvarga/sitemap_generator#302]
In continue, you answer me on Issue #301:
_It's not able to resolve the Content class. Are you running this inside Rails? If so, the rake tasks are included automatically for you and you don't need to add anything to the rake file. Make sure you have defined a Content model._

How define model and how run script inside Rails? 

I did everything about the instructions, but nothing happens.

**Comment by kjvarga** [comment]
Please don't open a new issue.  We can continue discussing on #301.  I closed the issue because the issue you are experiencing is not caused by a problem with the gem, but with how you are using it.  We can still discuss a solution for you on the #301 though.
