### ISSUE TITLE
Feature request: ability to separately specify hosting vs. generation paths

### ISSUE THREAD

**Issue by dogweather** [kjvarga/sitemap_generator#308]
For my multi-tenant site with subdomains, it would make sense to create sitemaps like this:

`tmp/sitemaps/site1/sitemap.xml.gz`

But serve them like this:

`https://site1.domain.com/sitemaps/sitemap.xml.gz`

I have no problem configuring my app for this.

However, I haven't figured out a way to configure sitemap_generator because of the interaction between `sitemaps_path` and `public_path`. AFAICT the file path will always appear in the hosting URL. The best I can come up with is this redundant URL, which gets placed in the index XML:

`https://site1.domain.com/sitemaps/site1/sitemap.xml.gz`

Are you open to a PR for this?

**EDIT**: I found a work-around which gets rid of the redundancy:

```ruby
  #
  # GENERATION
  #
  SitemapGenerator::Sitemap.default_host = url
  SitemapGenerator::Sitemap.public_path  = File.join('tmp', 'sitemap-generation', slug)

  #
  # GENERATION & FILE SERVING
  #
  SitemapGenerator::Sitemap.sitemaps_path = "sitemaps/"
```

This works by mimicking the file-serving structure. And I don't care about the redundant temp dirs structure. Not a bad hack. I'd prefer, though, to have separate config options for file serving vs. file generation.

**Comment by kjvarga** [comment]
You've done the right thing.  Arbitrary mapping from sitemaps to locations for writing vs serving is tricky.  I'm not sure what would be the best way to implement such a feature because it would tie together the SitemapNamer and the SitemapLocation, and add complexity there.  Let me know if you can think of a clean way to conceptualize it.
