### ISSUE TITLE
Failing rake task does not exit with failure

### ISSUE THREAD

**Issue by isles1217** [kjvarga/sitemap_generator#311]
Ran into an issue where the cron I had set up to generate sitemaps daily was failing, but wasn't alerting because the task wasn't exiting with a failure. The failure was occurring due to insufficient permissions to overwrite the existing sitemap files.

**Comment by niyando** [comment]
@isles1217 How did you get around the permission issue?

**Comment by isles1217** [comment]
@niyando the existing sitemap files at the time were created by our `root` user, the sitemaps were run by a different worker user. Running a  `chown` on each of the sitemap files we generated did the trick.
