### ISSUE TITLE
Set changefreq on default host?

### ISSUE THREAD

**Issue by key88sf** [kjvarga/sitemap_generator#313]
Is it possible to alter the changefreq value for the default host? It seems like it's only set to `always` and cannot be changed?

**Comment by kjvarga** [comment]
Sorry for the delay in responding.

You can set the `include_root` option to `false`.  There are a couple ways to do this, but most commonly:
`SitemapGenerator::Sitemap.include_root = false`.

Then you will need to manually add your root URL just as you would add any other links to your sitemaps, specifying your desired `changefreq` (see the `add` method in README).
