### ISSUE TITLE
Create group in another group (sitemap in sitemap)

### ISSUE THREAD

**Issue by edenisn** [kjvarga/sitemap_generator#319]
How can we create sitemap in another sitemap? For example:

```
<sitemap>
  <loc>
    https://mysite.com/test.xml
  </loc>
</sitemap>
<sitemap>
  <loc>
    https://mysite.com/another_test.xml
  </loc>
<sitemap>
```
and then in test.xml create something like this:

```
<sitemap>
  <loc>
    https://mysite.com/one.xml
  </loc>
</sitemap>
<sitemap>
  <loc>
    https://mysite.com/two.xml
  </loc>
<sitemap>

```

and final I would like to add link urls to one.xml and two.xml files.

```
group(filename: 'test') do
  group(filename: 'one') do
    add link
  end

  group(filename: 'one') do
    add link
  end
end

```
didn't work for me.

**Comment by kjvarga** [comment]
Hi.  Generally the structure of sitemaps is to have an index file with URLs pointing to files which themselves contain URLs.  The index file is optional - it's only needed if there are more than 50000 URLs.  For what purpose do you want to create the structure above?  It's not valid.
