### ISSUE TITLE
Issue submitting generated sitemap to Google Webmaster Console

### ISSUE THREAD

**Issue by patsch** [kjvarga/sitemap_generator#327]
I have added sitemaps using the gem to my project and have two issues.

When I run the rake task it seems to submit URLs to Google / Bing that lack the domain name after the https:// prefix:

> /www/whenismyga.me/prod/rails/current
> Using /home/railsuser/.rvm/gems/ruby-2.6.3 with gemset wimg
> railsuser@smallapps:/www/whenismyga.me/prod/rails/current$ rake sitemap:refresh
> In '/www/whenismyga.me/prod/rails/releases/20190526223840/public/':
> + sitemap.xml.gz                                        2915 links /    17.4 KB
> Sitemap stats: 2,915 links / 1 sitemaps / 0m01s
> 
> Pinging with URL 'https:/sitemap.xml.gz':
> Ping failed for Google: #<OpenURI::HTTPError: 400 Bad Request> (URL http://www.google.com/webmasters/tools/ping?sitemap=https%3A%2Fsitemap.xml.gz)

my config/sitemap.rb starts with:
```ruby
SitemapGenerator::Sitemap.default_host = "https:/whenismyga.me"
```

I then tried to submit the sitemap to Google's Search Console manually - and google basically complained about every single item:

<img width="960" alt="Screen Shot 2019-05-27 at 9 07 48 am" src="https://user-images.githubusercontent.com/124726/58388271-2b1c4700-8060-11e9-99bb-b90d7e5427a8.png">

However I cannot find anything wrong with the XML - the URL's loc tags look fine to me.
I have attached the gzipped sitemap file for reference.

Any suggestions what I may be doing wrong ?

[sitemap.xml.gz](https://github.com/kjvarga/sitemap_generator/files/3221300/sitemap.xml.gz)

**Comment by kjvarga** [comment]
Hi,

It looks like your default_host URL only has one backslash when it should
be two: http://

**Comment by patsch** [comment]
Bugger me....sorry - and thank you!
