### ISSUE TITLE
ampersand being escaped

### ISSUE THREAD

**Issue by kevupton** [kjvarga/sitemap_generator#328]
I have a url with query params, however the `&` symbol is being converted to `&amp;` when its being added to the sitemap. 
Is there a proper way to add a url with query params to the sitemap ?

**Comment by jrochkind** [comment]
That is the proper way already. As SiteMap is an XML file, it can't have a bare `&`, it needs to be escaped for XML. 

https://www.sitemaps.org/protocol.html#escaping

**Comment by kevupton** [comment]
ahh ok awesome haha thanks
