### ISSUE TITLE
ping fails when using fog-aws

### ISSUE THREAD

**Issue by 87Marc** [kjvarga/sitemap_generator#331]
When I run `rails sitemap:refresh`  with the following output 
```
Pinging with URL 'https://.s3.amazonaws.com/sitemap.xml.gz':
Ping failed for Google: #<OpenURI::HTTPError: 400 Bad Request> (URL http://www.google.com/webmasters/tools/ping?sitemap=https%3A%2F%2F.s3.amazonaws.com%2Fsitemap.xml.gz)
  Successful ping of Bing
```

It would appear that the S3_BUCKET ENV variable isn't being passed into the URL properly.  The sitemap generates as expected, but the ping fails for google at least.  Bing may not be validating the URL it is being passed.

**Comment by kjvarga** [comment]
Sorry I can't provide support for connection issues.

**Comment by 87Marc** [comment]
This is not a connectivity issue.  If you look at the output I included above you will notice that the URL that is being sent to Google (successfully no less) is malformed.  It starts with '.s3.' and URLs can't start with a dot.  For whatever reason, this is being called a "Ping" but it is actually a submission to Google webmaster tools.  

It is blocking the sitemap being submitted to google after it is created.

**Comment by kjvarga** [comment]
What is your sitemap config?  Id like to see how you are uploading your
site maps.  Thanks

**Comment by kjvarga** [comment]
It looks like you may not be configuring your `sitemaps_host` correctly. 
 That's the URL that is used to ping the search engines.

e.g. ```SitemapGenerator::Sitemap.sitemaps_host = "http://s3.amazonaws.com/sitemap-generator/"```

**Comment by kjvarga** [comment]
If you're configuring your bucket by an env variable then I don't see how SitemapGenerator will pick it up.   But at a minimum I'd need to see your configuration.
