### ISSUE TITLE
How to upload to the local disk of the server?

### ISSUE THREAD

**Issue by afuno** [kjvarga/sitemap_generator#334]
There is a Rails app with CarrierWave. The application is deployed to a server that has its own disk.

Please tell me how to properly configure your gem? In your examples we are talking only about remote services. But how, using CarrierWave, can I upload to the server’s local disk?

**Comment by jrochkind** [comment]
You want to save the sitemap to server's local disk in the public/ directory? You don't need carrierwave for that. Just run the rake task on the server, that is the default behavior, no special configuration is necessary.

**Comment by afuno** [comment]
@jrochkind I need CarrierWave. In addition to the sitemap there are still images and other files.

**Comment by jrochkind** [comment]
What do those images and other files have to do with sitemap_generator? I do not understand your question. 

(I am not the maintainer of this gem, just trying to help out.)

**Comment by afuno** [comment]
@jrochkind It's just that now I have all the uploads to the server going through CarrierWave. I think that for this gem do I need to use the same for upload?

**Comment by afuno** [comment]
@jrochkind But I was able to configure without CarrierWave.

**Comment by jrochkind** [comment]
This gem is for producing a sitemap.xml file for google or other search engines. It does not care where your uploads are and does not require you to change anything about them. 

A sitemap is a list of pages you are asking a search engine to index.
