### ISSUE TITLE
Missing items in sitemap when ID is greater than 10

### ISSUE THREAD

**Issue by redlightmikey** [kjvarga/sitemap_generator#336]
I have recently found my sitemap decrease massively in size. 

```
Profile.where.not(:is_active => nil).each do |profile|
        next if profile.id == 808
        next if profile.id == 1044
        puts "Adding #{profile.id}."
        add instructor_profile_path(profile), :lastmod => DateTime.now, :changefreq => 'daily'
end
```

I have this in the sitemap... and it prints out that it is adding 1000s of profiles but in the XML file it only goes up to profile/9. No longer going passed 10. 

Any ideas why?

**Comment by kjvarga** [comment]
That's odd.  I think it must have to do with your configuration or how you're adding your links.
