### ISSUE TITLE
Add new sitemaps to S3 hosted index every 4 hours

### ISSUE THREAD

**Issue by brianabaker** [kjvarga/sitemap_generator#337]
Hello! We run the sitemap generator from 1 single config file every morning, and host it on S3 (index set to true). Our site itself is hosted on Heroku. A lot of our sitemaps are user-generated dynamic listing pages, and we want to programmatically create and add new listing sitemaps every 4 hours. 

I've looked into this issue: https://github.com/kjvarga/sitemap_generator/issues/315, and it looks like a solution would be to fetch the hosted sitemap index, parse it, make the new sitemaps, add them to the index, and push that back up to S3. 

Is there an easier way to do this? Can I utilize `LinkSet` or `add_to_index` somehow? 

I was thinking we'd make a new sitemap config file (index set to true) and have that single file run every 4 hours (pinging search engines too), but I don't want to overwrite the entire file each time. I'd also like to attach a link to this "new listings sitemap index" in our main sitemap index file, and have it all hosted in the same folder in our S3 bucket. What would be the best way to accomplish this?

**Comment by rjhancock** [comment]
You're probably better off just running it every night and overwriting. The search engines only queue your site for processing when you ping so it could still take a few days before they actually get to it.
