### ISSUE TITLE
How to remove some sitemaps in urlset tag?

### ISSUE THREAD

**Issue by ducpt1012** [kjvarga/sitemap_generator#341]
@kjvarga 
I only need to define `xmlns:image` and remove other sitemaps (video, news, mobile...) in the urlset tag. But I don't find the place to config to disable/hide those. 
How to remove some sitemaps in urlset tag?
Thanks

This is default format when buidling:
`<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xmlns:video="http://www.google.com/schemas/sitemap-video/1.1" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9" xmlns:mobile="http://www.google.com/schemas/sitemap-mobile/1.0" xmlns:pagemap="http://www.google.com/schemas/sitemap-pagemap/1.0" xmlns:xhtml="http://www.w3.org/1999/xhtml">`

**Comment by kjvarga** [comment]
Hi.  Why do you need to remove those tags?

**Comment by ducpt1012** [comment]
I wonder those attributes are necessary when my site is just defined the URL of site and image and without video, news...

So, I find this place. It is the default of format in this gem.
https://github.com/kjvarga/sitemap_generator/blob/0b847f1e7a544ea8ef87bb643a732e30a07a14c9/lib/sitemap_generator/builder/sitemap_file.rb#L28-L42

**Comment by kjvarga** [comment]
Those attributes aren’t necessary if you’re  not using them, but they do no
harm, and they only add a few bytes.  I think you should just ignore them.

**Comment by ducpt1012** [comment]
Yes. I got it. Thank you for responding.

**Comment by DumasOlivier** [comment]
Hey, I know this is closed but would be great to have an option to disable some attributes if not used 😄 
Thank you anyway for this great gem 🙏
