### ISSUE TITLE
Do no raise runtime errors when not requiring additional storages, raise LoadError instead

### ISSUE THREAD

**Issue by apuntovanini** [kjvarga/sitemap_generator#344]
Similar to this
https://github.com/sorbet/sorbet/issues/1820

**Comment by kjvarga** [comment]
The sitemap generator code does not require modules used in the adapters.  It looks for constants which should already be defined.  So that doesn't meet the use case for a LoadError https://ruby-doc.org/core-2.5.1/LoadError.html.  It actually raises a StandardError
