### ISSUE TITLE
Link to different domain/subdomain

### ISSUE THREAD

**Issue by c0mrade** [kjvarga/sitemap_generator#347]
I have my docs located at docs.mydomain.com, how can I add that to sitemap? I mean it's external url but really it's part of my website system as a whole

**Comment by kjvarga** [comment]
All URLs in a sitemap must belong to the same domain, unless you can prove that you own both domains.  You can learn more about that online.  But see https://github.com/kjvarga/sitemap_generator#adding-links that allows you to set the host on the links you add to your sitemap.
