### ISSUE TITLE
Add "endpoint" option to AWS SDK Adapter for DigitalOcean spaces compatibility

### ISSUE THREAD

**Issue by jmarbach** [kjvarga/sitemap_generator#348]
As per this question on StackOverflow: https://stackoverflow.com/questions/61276322/cant-specify-digitalocean-endpoint-in-sitemap-generator-s3-aws-adaptor/61577866#61577866

The endpoint option is needed on the AWS SDK Adapter so that sitemaps can be uploaded to DigitalOcean Spaces instead of AWS S3.

**Comment by jmarbach** [comment]
Looks like there is already an open PR to fix this issue: https://github.com/kjvarga/sitemap_generator/pull/325

**Comment by kjvarga** [comment]
Released in v6.1.1
