### ISSUE TITLE
v6.1.1 ping failed under Ruby 2.7

### ISSUE THREAD

**Issue by byungjikroh** [kjvarga/sitemap_generator#352]
An error about 'Ping failed for Google: #<NoMethodError: private method `open' called for URI:Module>' at v6.1.1 because of a patch to support URI.open instead of depreciated Kernel#open (https://github.com/kjvarga/sitemap_generator/pull/342).

But Ruby version below than 2.7 (I'm not sure), there is no URI.open method so it causes errors when ping to Google or Bing. 

Please patch to support Kernel#open for Ruby version below than 2.7.

**Comment by kjvarga** [comment]
Thanks for the report!

**Comment by kjvarga** [comment]
@Envek it looks like this was missed in your implementation.  Are you able to suggest a fix?

**Comment by Envek** [comment]
Ah, `URI.open` was added only in Ruby 2.5, quite recently: https://rubyreferences.github.io/rubychanges/2.5.html#network-and-web

**Comment by byungjikroh** [comment]
So it needs to update to support under Ruby 2.5 or to set 'required Ruby version' to Ruby 2.5 and above. 

Since I use below Ruby 2.5, I prefer supporting old Ruby versions.

**Comment by Envek** [comment]
Added support for old rubies in https://github.com/kjvarga/sitemap_generator/pull/353

---

@byungjikroh, please note that rubies older than 2.5 are not supported anymore:

> WARNING: ruby-2.4.10 is past its end of life and is now unsupported.
> It no longer receives bug fixes or critical security updates.

So it is better to upgrade anyway

**Comment by byungjikroh** [comment]
Sure. Thanks a lot. 😀

**Comment by kjvarga** [comment]
Fixed in v6.1.2.  It's now backwards compatible with older Rubies.  Thanks for the report.
