### ISSUE TITLE
Trailing slash added to root URL only

### ISSUE THREAD

**Issue by svoop** [kjvarga/sitemap_generator#360]
My site doesn't use trailing slashes at all, in fact, they trigger 301 to their non-trailing-slash counterpart.

This works fine with the sitemap_generator for the most part, however, the root URL behaves differently:

```
SitemapGenerator::Sitemap.default_host = 'https://example.com'
SitemapGenerator::Sitemap.sitemaps_path = 'sitemaps/'
SitemapGenerator::Sitemap.verbose = false

SitemapGenerator::Sitemap.create do
  I18n.available_locales.each do |locale|
    group filename: locale do
      add "?locale=#{locale}", priority: 1.0, changefreq: 'always'
      add projects_path(locale: locale), priority: 0.8, changefreq: 'always'
      (...)
```

The above results in:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<urlset (...)>
  <url>
    <loc>https://example.com/?locale=de</loc>
    <lastmod>2020-08-27T12:34:07+02:00</lastmod>
    <changefreq>always</changefreq>
    <priority>1.0</priority>
  </url>
  <url>
    <loc>https://example.com/projects?locale=de</loc>
    <lastmod>2020-08-27T12:34:07+02:00</lastmod>
    <changefreq>always</changefreq>
    <priority>0.7</priority>
  </url>
  (...)
```

Note that a trailing slash is added for the first (root) entry `.com/?locale` while all other entries don't get a trailing slash `projects?locale`.

If this is a feature, maybe you see a workaround to get the root entry added without the trailing slash: `https://example.com?locale=de`.

Loosely related to #355

PS: Very nice gem, thanks a bunch for it! 👍

**Comment by jrochkind** [comment]
`https://example.com?locale=de` is not a legal URL. Or if it is, it would be trying to say that your hostname is `example.com?locale=de`.  

I just tried to load `http://example.com?locale=de` in Chrome, and Chrome immediatey converted it to `https://example.com/?foo=bar` before actually loading it, thinking I must have meant the latter. 

Are you sure you really want you want you want? Are you sure the `.com/?locale` URL doesn't work on your site?

**Comment by svoop** [comment]
Jeez, you're right, I've never thought about this. That's why for the root URL (and only for the root URL) Google considers with or without trailing slash to be the same page.

In that case, that's the way it has to be. Thanks for the hint!

**Comment by svoop** [comment]
For reference, the RFC confirming this are [1738 (URL)](https://tools.ietf.org/html/rfc1738) and [2396 (URI)](https://tools.ietf.org/html/rfc2396).
