### ISSUE TITLE
Error when submitting my sitemap.xml.gz to Google Search Console

### ISSUE THREAD

**Issue by Bertrand-Bichat** [kjvarga/sitemap_generator#363]
Hi,

I use the gem "sitemap_generator" to generate only one sitemap on my website (no index sitemap). This sitemap is compress with gzip and located in my "public" folder. I have included "Sitemap: https://www.holivia.fr/sitemap.xml.gz" to my robots.txt file.

My stack is Rails 5.2.4.1 and Ruby 2.6.6

When I submit my sitemap URL (/sitemap.xml.gz) to the Google Search Console, it raise an error : "unable to recover sitemap" or "unable to read the sitemap".

Can you help me, what should I do to solve this problem ?

**Comment by thanhtoan1196** [comment]
I also got the error

When using the sitemap-generator to create a sitemap, the last file was read successfully, the rest was corrupted
https://api.ngontinh24.com/build/sitemaps/ngontinh/sitemap.xml.gz

![image](https://user-images.githubusercontent.com/16433547/102084727-2983c100-3e48-11eb-8743-8589554ebe05.png)

The steps to reproduce
```
Rake::Task["sitemap:refresh"].invoke
```

Logs 
```
+ build/sitemaps/ngontinh/sitemap.xml.gz                3 sitemaps /  267 Bytes                                                                                                                                       
│ Sitemap stats: 142,625 links / 3 sitemaps / 1m29s
```

**Comment by Bertrand-Bichat** [comment]
I have solve my problem by removing the Gzip compression in order to have sitemap.xml url AND by changing my robots.txt file to this : 

```
Sitemap: https://www.holivia.fr/sitemap.xml

User-agent: *
Disallow:
```

**Comment by azeem6755** [comment]
Add robots.txt to your root, it will work.

**Comment by MiroBabic** [comment]
I have populated robots.txt but get same error
I also tried not gziped files but same. Google can fetch sitemap index but cannot fetch actual sitemaps
