### ISSUE TITLE
Can't generate sitemap on Rails 6.1 and Ruby 3.0

### ISSUE THREAD

**Issue by nortonandreev** [kjvarga/sitemap_generator#371]
I have migrated to Rails 6.1 and Ruby 3.0. Unfortunately, I am getting an error when running "rake sitemap:refresh". Not sure if the problem is caused due to the Ruby update or if an update of the google-cloud-storage is not compatible with the sitemap_generator's google_storage_adapter.

<img width="1608" alt="Screenshot 2021-02-09 at 05 04 10" src="https://user-images.githubusercontent.com/34094428/107310214-a9b75300-6a94-11eb-9b49-be2edd6e993d.png">

**Comment by kjvarga** [comment]
It looks like there's a breaking change in the Google Cloud Storage gem that is breaking the adapter.

**Comment by 9mm** [comment]
Yep same...

**Comment by kjvarga** [comment]
This has been addressed in v6.2.0
