### ISSUE TITLE
Produces different binary output on same uncompressed output

### ISSUE THREAD

**Issue by artagnon** [kjvarga/sitemap_generator#374]
Hi,

When `compress = true`, the `sitemap.xml.gz` generated on every run is binary-different, although the uncompressed `sitemap.xml` is the same; I have `include_root = false`. This issue is particularly annoying for me, because I check in my `sitemap.xml.gz`, and a vacuous diff is generated sometimes.

Thanks.

**Comment by kjvarga** [comment]
This appears to be caused by some file metadata being included by GZip.  It might be worth trying to use the `-n` option to Gzip to omit the filename and timestamp and see if that addresses the issue.

https://medium.com/@mpreziuso/is-gzip-deterministic-26c81bfd0a49

**Comment by artagnon** [comment]
Thanks for digging this up; I've decided to switch off gzip for my sitemap.
