### ISSUE TITLE
Bing URL outdated

### ISSUE THREAD

**Issue by strobilomyces** [kjvarga/sitemap_generator#381]
I'm not sure when this started, but when the sitemap generator pings Bing, I'm getting:

`Ping failed for Bing: #<OpenURI::HTTPError: 410 Gone>`

Updating the URL to `https://www.bing.com/webmaster/ping.aspx?sitemap=%s` fixes the issue.

**Comment by dan-jensen** [comment]
Check out this [ctrl.blog article](https://www.ctrl.blog/entry/sitemap-ping-indexnow.html) for a very nice explanation of why this is happening.  I posted [some technical details in the PR](https://github.com/kjvarga/sitemap_generator/pull/382#issuecomment-1006058971).

**Comment by kjvarga** [comment]
Merged in https://github.com/kjvarga/sitemap_generator/pull/386

**Comment by strobilomyces** [comment]
Thanks!

**Comment by kjvarga** [comment]
Released in 6.2.0

**Comment by da2x** [comment]
> Updating the URL to `https://www.bing.com/webmaster/ping.aspx?sitemap=%s` fixes the issue.

As stated in the article, that endpoint is used to submit brand new and not updated sitemaps. Bing has just dropped support for sitemap pings.
