### ISSUE TITLE
Ping failed for Bing: #<OpenURI::HTTPError: 410 Gone>

### ISSUE THREAD

**Issue by mikhailushka** [kjvarga/sitemap_generator#391]
Hi, this is more of a question than an issue.

Around 12/22/2021, we started to notice interesting sitemap generation logs:
`Ping failed for Bing: #<OpenURI::HTTPError: 410 Gone> (URL http://www.bing.com/ping?sitemap=https%3A%2F%2Fwww.some.ru%2Fsitemaps%2Fvideo%2Fsitemap. xml.gz)`

If we can trust https://www.ctrl.blog/entry/sitemap-ping-indexnow.html, then microsoft turned off the public API (http://www.bing.com/ping) that is currently used for ping, instead they uses IndexNow.

What do you think about this?

**Comment by kjvarga** [comment]
Yes you are correct.  In v6.2.0 the Bing url was updated to one that still
works but is for notification of new sitemaps only, see
https://github.com/kjvarga/sitemap_generator/pull/386.  But IndexNow
appears to be the better way to do it.  It’s just a lot more complicated to
implement and requires setup on your part as well, so I’m unlikely to
implement it, but am open to a PR.

**Comment by kjvarga** [comment]
Bing ping has been removed in [v6.3.0](https://github.com/kjvarga/sitemap_generator/blob/master/CHANGES.md#630)
