### ISSUE TITLE
Feature Request: Remove unwanted options

### ISSUE THREAD

**Issue by muchaya** [kjvarga/sitemap_generator#392]
Not really an issue, but a small feature request.

We have encountered a situation were we'd like to remove `lastmod` for specific pages. The current behaviour defaults to `Time.now` if not explicitly set as an option to` add`. It would be great if there would be a way to completely remove the options that google may deem to be optional.

Thanks for all your work maintaining this gem @kjvarga!

**Comment by kjvarga** [comment]
@muchaya thanks for the kudos! 

I can see how it would be useful to allow the defaults to be configurable.  For now you can pass `lastmod: nil` in your call to `add` to prevent the lastmod property being set on links.

**Comment by muchaya** [comment]
Hey @kjvarga, we tried passing `nil` in our call to `add ` but it still includes the `lastmod` option in the schema.

**Comment by kjvarga** [comment]
Can you show me your site map config?  It was working for me.

**Comment by muchaya** [comment]
Hey @kjvarga , sorry for the late response. It was working but we were probably reading from on old sitemap in a local env or something. We deleted the old sitemaps and it worked. Thanks for your help.
