### ISSUE TITLE
GoogleStorageAdapter - Can't create sitemap on buckets with uniform bucket-level access enabled

### ISSUE THREAD

**Issue by tkhsh** [kjvarga/sitemap_generator#396]
When sitemap files are uploaded to Google Cloud Storage and uniform bucket-level access is enabled on the bucket, the following error occurs.
```
Google::Cloud::InvalidArgumentError: invalid: Cannot insert legacy ACL for an object when uniform bucket-level access is enabled. Read more at https://cloud.google.com/storage/docs/uniform-bucket-level-access
```

Currently, sitemap_generator always grants an ACL when creating a sitemap object, so it would be nice to specify an option that allows to create an object without an ACL.

**Comment by andrewchen5678** [comment]
+1 just encountered this issue

**Comment by kjvarga** [comment]
@tkhsh @andrewchen5678 [v6.3.0](https://github.com/kjvarga/sitemap_generator/blob/master/CHANGES.md#630) allows you to configure the `acl` option.  Could you try specifying `acl: nil` in the options to disable acl being set?  If that doesn't work, we probably just need to `compress` the options we send to `upload_file` to remove nil options.  If you could confirm that it would be helpful.  Thanks.

**Comment by tkhsh** [comment]
@kjvarga 
I tried uploading with `acl: nil` and it was successful. Thank you.
