### ISSUE TITLE
Allow disable acl for S3 bucket

### ISSUE THREAD

**Issue by andrewchen5678** [kjvarga/sitemap_generator#398]
Currently it is forcing S3 bucket to have acl = public read, which is not desired for some setup.

It'll be helpful to be able to disable that option.

https://github.com/kjvarga/sitemap_generator/blob/aa69709ac631466b1d7562195343e7cffe1b5b59/lib/sitemap_generator/adapters/aws_sdk_adapter.rb#L43

**Comment by kjvarga** [comment]
@andrewchen5678 you can now configure the `acl` option in [v6.3.0](https://github.com/kjvarga/sitemap_generator/blob/master/CHANGES.md#630)
