### ISSUE TITLE
【Worked】Ping failed for Bing: #<OpenURI::HTTPError: 410 Gone>

### ISSUE THREAD

**Issue by mah666hhh** [kjvarga/sitemap_generator#403]
Error when running `rake sitemap: refresh`` Ping failed for Bing: # <OpenURI :: HTTPError: 410 Gone> `
 Has occurred.

```
 $ bundle exec rake sitemap:refresh
In '/Users/xxx/workspace/ccc/vvv/':
+ sitemaps/sitemap.xml.gz                                 15 links /  561 Bytes
Sitemap stats: 15 links / 1 sitemaps / 0m01s

Pinging with URL 'https://s3-ap-northeast-1.amazonaws.com/sitemaps/sitemap.xml.gz':
  Successful ping of Google


Ping failed for Bing: #<OpenURI::HTTPError: 410 Gone> (URL http://www.bing.com/webmaster/ping.aspx?sitemap=https%3A%2F%2Fs3-ap-northeast-1.amazonaws.com%2Fsitemaps%2Fsitemap.xml.gz)
```

If you check the ping destination with the current Bing Webmaster Tools,

```
http://www.bing.com/webmasters/submiturl?siteUrl=
```

The URL is like this,

I suspect this is currently the correct ping destination URL for Bing.（in japan.）

![bing ウェブマスターツール ping送信先 url](https://user-images.githubusercontent.com/43061845/172779469-f6ee8d52-3c53-449c-a036-af21f8ffd167.jpg)

```
# In gem, not working.
"http://www.bing.com/webmaster/ping.aspx?sitemap=%s"

# In Bing Webmaster Tools, Work.
"http://www.bing.com/webmasters/submiturl?siteUrl=%s"
```

<br>

for that reason,

When creating an instance of SitemapGenerator :: Sitemap

I think I need to change the parameters of search_engines: bing: parameters.

```
{ search_engines: { bing: "http://www.bing.com/webmasters/submiturl?siteUrl=%s" } }
```

- e.g.

```rb
SitemapGenerator::Sitemap.create({ search_engines: { google: "http://www.google.com/webmasters/tools/ping?sitemap=%s", bing: "http://www.bing.com/webmasters/submiturl?siteUrl=%s" } }) do
  add 'page_url'
end
```

Running `rake sitemap: refresh` as above worked for me.

```
$ bundle exec rake sitemap:refresh
In '/Users/xxx/workspace/ccc/vvv/':
+ sitemaps/sitemap.xml.gz                                 15 links /  561 Bytes
Sitemap stats: 15 links / 1 sitemaps / 0m01s

Pinging with URL 'https://s3-ap-northeast-1.amazonaws.com/sitemaps/sitemap.xml.gz':
  Successful ping of Google
  Successful ping of Bing
```

I think the corrections are as follows.

https://github.com/kjvarga/sitemap_generator/blob/master/lib/sitemap_generator/link_set.rb#L129

![スクリーンショット 2022-06-09 15 35 42](https://user-images.githubusercontent.com/43061845/172780702-c5832e60-4abc-465b-89be-a85dac5bf168.jpg)

```
# not working.
:bing           => "http://www.bing.com/webmaster/ping.aspx?sitemap=%s"
```

```
# Work.
:bing           => "http://www.bing.com/webmasters/submiturl?siteUrl=%s"
```

Thank you.

**Comment by viviana-aline** [comment]
Seems like the Bing sitemap ping is deprecated https://blogs.bing.com/webmaster/may-2022/Spring-cleaning-Removed-Bing-anonymous-sitemap-submission

**Comment by thanhtoan1196** [comment]
any updates?

**Comment by danmarx** [comment]
Bing looks to be pingable via IndexNow - https://www.indexnow.org/faq

https://www.bing.com/indexnow?url=url-changed&key=your-key

**Comment by kjvarga** [comment]
Hi all, Bing is no longer accepting direct pings, so it has been removed in [v6.3.0](https://github.com/kjvarga/sitemap_generator/blob/master/CHANGES.md#630).  

Until we get support for IndexNow we won't be able to ping Bing.
