### ISSUE TITLE
Google search correct ping url

### ISSUE THREAD

**Issue by unlimit** [kjvarga/sitemap_generator#418]
Hi!
Accordingly to https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap, correct ping url for google is `https://www.google.com/ping?sitemap=FULL_URL_OF_SITEMAP`, but this gem uses `http://www.google.com/webmasters/tools/ping?sitemap=%s`.   https://github.com/kjvarga/sitemap_generator/blob/28dd22c48597f8b2a44cbc7e20685e84975fe75b/lib/sitemap_generator/link_set.rb#L128
What is the correct url?

**Comment by davidpan** [comment]
I tested it and both addresses work fine.

**Comment by nanego** [comment]
We can certainly close this issue as pings to Google have been deprecated and all requests to these endpoints will result in a 404 error:
https://developers.google.com/search/blog/2023/06/sitemaps-lastmod-ping

**Comment by n-rodriguez** [comment]
Done in https://github.com/kjvarga/sitemap_generator/pull/444
