### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by n-rodriguez** [kjvarga/sitemap_generator#436]
Hi there!

Is this project still maintained?

Thank you!

**Comment by n-rodriguez** [comment]
Yes :)

**Comment by partounian** [comment]
Why did you comment yes if no commit in 2 years?

**Comment by kjvarga** [comment]
@partounian, @n-rodriguez has been added as a collaborator to the project and will be helping to extend and maintain it.  Unfortunately I don't have the time to focus on this project anymore.

**Comment by partounian** [comment]
That's great to hear :)

I have some spare time nowadays so I can help as well

**Comment by kjvarga** [comment]
@partounian thanks for your help!  Appreciate it

**Comment by partounian** [comment]
I don't know if I have the permissions on rubygems. Can double check this week

**Comment by kjvarga** [comment]
@n-rodriguez once you have a release candidate just let me know and I'll verify the code changes don't do anything unwanted (trust, but verify) and release the gem.  Please make sure it's well tested and the new version follows semantic versioning.  Especially if it does not maintain backwards compatibility/introduces a breaking change then we should use a major version release.

**Comment by n-rodriguez** [comment]
> [@n-rodriguez](https://github.com/n-rodriguez) once you have a release candidate just let me know and I'll verify the code changes don't do anything unwanted (trust, but verify) and release the gem. Please make sure it's well tested and the new version follows semantic versioning. Especially if it does not maintain backwards compatibility/introduces a breaking change then we should use a major version release.

sure! thank you!

**Comment by n-rodriguez** [comment]
Changelog: https://github.com/kjvarga/sitemap_generator/compare/v6.3.0...master
