### ISSUE TITLE
How to disable compression and create uncompressed files by rake task?

### ISSUE THREAD

**Issue by lexer** [kjvarga/sitemap_generator#64]

**Comment by Oimah** [comment]
Hi kjvarga, I want to split my sitemap into files of 1000 urls each depending on the size of my record but no file will have more than 1000 urls in it. The number of files depends on the record size. Any functionality to do that now?

**Comment by kjvarga** [comment]
You're off topic for this thread.  I actually have this virtually ready to go https://github.com/kjvarga/sitemap_generator/pull/262.  For reference #188
