### ISSUE TITLE
Include only used XML schemas

### ISSUE THREAD

**Issue by boretom** [kjvarga/sitemap_generator#72]
Not an issue but an idea to keep the generated XML schema entry (urlset) short : Include only the XML schemas that are actually used in the pages. Or if that adds too much processing, options to disable them manually.

I have a simple website which I created using [stasis](http://www.stasis.me) and I saw that all the video, audio, etc schemas are added to sitemap#.xml although I don't use any of 'em.

**Comment by dezmathio** [comment]
@kjvarga is this still the case 3 years later? Is the urlset always auto-generated regardless of flags?

**Comment by kjvarga** [comment]
That's right, the urlset is static.  It's really not a priority for me just
to save a few bytes, so unless someone wants to do it, I'm not concerned.
Typically sitemaps are quite large so having a few extra strings in there
is NABID.

On Thu, Jan 15, 2015 at 7:29 AM, Josiah Anjos <notifications@github.com>
wrote:

> @kjvarga <https://github.com/kjvarga> is this still the case 3 years
> later? Is the urlset always auto-generated regardless of flags?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kjvarga/sitemap_generator/issues/72#issuecomment-70102570>
> .
>



-- 
Karl Varga
e: kjvarga@gmail.com
w: kjvarga.blogspot.com
c: +1.250.884.9895
Skype: kjvarga
